/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Request payload for creating a workflow run.
 */
@JsonPropertyOrder({
  CreateWorkflowRun.JSON_PROPERTY_INPUTS,
  CreateWorkflowRun.JSON_PROPERTY_THREAD,
  CreateWorkflowRun.JSON_PROPERTY_PRIORITY,
  CreateWorkflowRun.JSON_PROPERTY_ENVIRONMENT,
  CreateWorkflowRun.JSON_PROPERTY_ENV_VARS,
  CreateWorkflowRun.JSON_PROPERTY_METADATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CreateWorkflowRun {
  public static final String JSON_PROPERTY_INPUTS = "inputs";
  @jakarta.annotation.Nonnull
  private Map<String, String> inputs = new HashMap<>();

  public static final String JSON_PROPERTY_THREAD = "thread";
  private JsonNullable<UUID> thread = JsonNullable.<UUID>undefined();

  /**
   * Processing priority.
   */
  public enum PriorityEnum {
    ONSITE(String.valueOf("onsite")),
    
    NORMAL(String.valueOf("normal")),
    
    LOW(String.valueOf("low"));

    private String value;

    PriorityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PriorityEnum fromValue(String value) {
      for (PriorityEnum b : PriorityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PRIORITY = "priority";
  @jakarta.annotation.Nullable
  private PriorityEnum priority = PriorityEnum.NORMAL;

  public static final String JSON_PROPERTY_ENVIRONMENT = "environment";
  private JsonNullable<String> environment = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ENV_VARS = "envVars";
  @jakarta.annotation.Nullable
  private Map<String, String> envVars = new HashMap<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @jakarta.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public CreateWorkflowRun() { 
  }

  public CreateWorkflowRun inputs(@jakarta.annotation.Nonnull Map<String, String> inputs) {
    this.inputs = inputs;
    return this;
  }

  public CreateWorkflowRun putInputsItem(String key, String inputsItem) {
    if (this.inputs == null) {
      this.inputs = new HashMap<>();
    }
    this.inputs.put(key, inputsItem);
    return this;
  }

  /**
   * Key-value map of input variable names to their values.
   * @return inputs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Map<String, String> getInputs() {
    return inputs;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInputs(@jakarta.annotation.Nonnull Map<String, String> inputs) {
    this.inputs = inputs;
  }


  public CreateWorkflowRun thread(@jakarta.annotation.Nullable UUID thread) {
    this.thread = JsonNullable.<UUID>of(thread);
    return this;
  }

  /**
   * Thread ID to continue a multi-turn conversation. Omit to start a new thread.
   * @return thread
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public UUID getThread() {
        return thread.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_THREAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getThread_JsonNullable() {
    return thread;
  }
  
  @JsonProperty(JSON_PROPERTY_THREAD)
  public void setThread_JsonNullable(JsonNullable<UUID> thread) {
    this.thread = thread;
  }

  public void setThread(@jakarta.annotation.Nullable UUID thread) {
    this.thread = JsonNullable.<UUID>of(thread);
  }


  public CreateWorkflowRun priority(@jakarta.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Processing priority.
   * @return priority
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIORITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PriorityEnum getPriority() {
    return priority;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIORITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriority(@jakarta.annotation.Nullable PriorityEnum priority) {
    this.priority = priority;
  }


  public CreateWorkflowRun environment(@jakarta.annotation.Nullable String environment) {
    this.environment = JsonNullable.<String>of(environment);
    return this;
  }

  /**
   * Environment that scopes which webhooks fire and which environment variables the run can access. Uses the default environment when omitted.
   * @return environment
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getEnvironment() {
        return environment.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getEnvironment_JsonNullable() {
    return environment;
  }
  
  @JsonProperty(JSON_PROPERTY_ENVIRONMENT)
  public void setEnvironment_JsonNullable(JsonNullable<String> environment) {
    this.environment = environment;
  }

  public void setEnvironment(@jakarta.annotation.Nullable String environment) {
    this.environment = JsonNullable.<String>of(environment);
  }


  public CreateWorkflowRun envVars(@jakarta.annotation.Nullable Map<String, String> envVars) {
    this.envVars = envVars;
    return this;
  }

  public CreateWorkflowRun putEnvVarsItem(String key, String envVarsItem) {
    if (this.envVars == null) {
      this.envVars = new HashMap<>();
    }
    this.envVars.put(key, envVarsItem);
    return this;
  }

  /**
   * Runtime environment variable overrides for this run. Keys must be UPPER_CASE. At most 50 entries, 64 KB total.
   * @return envVars
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENV_VARS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getEnvVars() {
    return envVars;
  }


  @JsonProperty(value = JSON_PROPERTY_ENV_VARS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvVars(@jakarta.annotation.Nullable Map<String, String> envVars) {
    this.envVars = envVars;
  }


  public CreateWorkflowRun metadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public CreateWorkflowRun putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Arbitrary key-value metadata attached to the run. Values can be strings or arrays of strings.
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@jakarta.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  /**
   * Return true if this CreateWorkflowRun object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateWorkflowRun createWorkflowRun = (CreateWorkflowRun) o;
    return Objects.equals(this.inputs, createWorkflowRun.inputs) &&
        equalsNullable(this.thread, createWorkflowRun.thread) &&
        Objects.equals(this.priority, createWorkflowRun.priority) &&
        equalsNullable(this.environment, createWorkflowRun.environment) &&
        Objects.equals(this.envVars, createWorkflowRun.envVars) &&
        Objects.equals(this.metadata, createWorkflowRun.metadata);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputs, hashCodeNullable(thread), priority, hashCodeNullable(environment), envVars, metadata);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWorkflowRun {\n");
    sb.append("    inputs: ").append(toIndentedString(inputs)).append("\n");
    sb.append("    thread: ").append(toIndentedString(thread)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    envVars: ").append(toIndentedString(envVars)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `inputs` to the URL query string
    if (getInputs() != null) {
      for (String _key : getInputs().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sinputs%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getInputs().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getInputs().get(_key)))));
      }
    }

    // add `thread` to the URL query string
    if (getThread() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthread%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThread()))));
    }

    // add `priority` to the URL query string
    if (getPriority() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spriority%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPriority()))));
    }

    // add `environment` to the URL query string
    if (getEnvironment() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%senvironment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnvironment()))));
    }

    // add `envVars` to the URL query string
    if (getEnvVars() != null) {
      for (String _key : getEnvVars().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%senvVars%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getEnvVars().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getEnvVars().get(_key)))));
      }
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      for (String _key : getMetadata().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%smetadata%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getMetadata().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getMetadata().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

