/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * CreatePromptRunResponse
 */
@JsonPropertyOrder({
  CreatePromptRunResponse.JSON_PROPERTY_ID,
  CreatePromptRunResponse.JSON_PROPERTY_THREAD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class CreatePromptRunResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_THREAD = "thread";
  @jakarta.annotation.Nonnull
  private UUID thread;

  public CreatePromptRunResponse() { 
  }

  public CreatePromptRunResponse id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Prompt run ID
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public CreatePromptRunResponse thread(@jakarta.annotation.Nonnull UUID thread) {
    this.thread = thread;
    return this;
  }

  /**
   * Thread ID for multi-turn runs
   * @return thread
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_THREAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getThread() {
    return thread;
  }


  @JsonProperty(value = JSON_PROPERTY_THREAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setThread(@jakarta.annotation.Nonnull UUID thread) {
    this.thread = thread;
  }


  /**
   * Return true if this CreatePromptRunResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatePromptRunResponse createPromptRunResponse = (CreatePromptRunResponse) o;
    return Objects.equals(this.id, createPromptRunResponse.id) &&
        Objects.equals(this.thread, createPromptRunResponse.thread);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, thread);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatePromptRunResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    thread: ").append(toIndentedString(thread)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `thread` to the URL query string
    if (getThread() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthread%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThread()))));
    }

    return joiner.toString();
  }
}

