/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * One emit-tool call: the tool name and its schema-validated payload.
 */
@JsonPropertyOrder({
  EmittedItem.JSON_PROPERTY_TOOL,
  EmittedItem.JSON_PROPERTY_PAYLOAD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class EmittedItem {
  public static final String JSON_PROPERTY_TOOL = "tool";
  @jakarta.annotation.Nonnull
  private String tool;

  public static final String JSON_PROPERTY_PAYLOAD = "payload";
  @jakarta.annotation.Nonnull
  private Object payload;

  public EmittedItem() { 
  }

  public EmittedItem tool(@jakarta.annotation.Nonnull String tool) {
    this.tool = tool;
    return this;
  }

  /**
   * The emit tool that produced this payload.
   * @return tool
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOOL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTool() {
    return tool;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTool(@jakarta.annotation.Nonnull String tool) {
    this.tool = tool;
  }


  public EmittedItem payload(@jakarta.annotation.Nonnull Object payload) {
    this.payload = payload;
    return this;
  }

  /**
   * The payload — the tool-call arguments, verbatim.
   * @return payload
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Object getPayload() {
    return payload;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYLOAD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPayload(@jakarta.annotation.Nonnull Object payload) {
    this.payload = payload;
  }


  /**
   * Return true if this EmittedItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmittedItem emittedItem = (EmittedItem) o;
    return Objects.equals(this.tool, emittedItem.tool) &&
        Objects.equals(this.payload, emittedItem.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tool, payload);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmittedItem {\n");
    sb.append("    tool: ").append(toIndentedString(tool)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tool` to the URL query string
    if (getTool() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stool%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTool()))));
    }

    // add `payload` to the URL query string
    if (getPayload() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spayload%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPayload()))));
    }

    return joiner.toString();
  }
}

