/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.HttpHeader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * External HTTP call tool.
 */
@JsonPropertyOrder({
  HttpCall.JSON_PROPERTY_PARAMS_SCHEMA,
  HttpCall.JSON_PROPERTY_URL,
  HttpCall.JSON_PROPERTY_METHOD,
  HttpCall.JSON_PROPERTY_HEADERS,
  HttpCall.JSON_PROPERTY_NAME,
  HttpCall.JSON_PROPERTY_DESCRIPTION,
  HttpCall.JSON_PROPERTY_FAIL_FAST,
  HttpCall.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class HttpCall {
  public static final String JSON_PROPERTY_PARAMS_SCHEMA = "paramsSchema";
  @jakarta.annotation.Nonnull
  private String paramsSchema;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull
  private String url;

  /**
   * Gets or Sets method
   */
  public enum MethodEnum {
    GET(String.valueOf("GET")),
    
    POST(String.valueOf("POST")),
    
    PUT(String.valueOf("PUT")),
    
    PATCH(String.valueOf("PATCH")),
    
    DELETE(String.valueOf("DELETE"));

    private String value;

    MethodEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MethodEnum fromValue(String value) {
      for (MethodEnum b : MethodEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_METHOD = "method";
  @jakarta.annotation.Nonnull
  private MethodEnum method;

  public static final String JSON_PROPERTY_HEADERS = "headers";
  @jakarta.annotation.Nullable
  private List<HttpHeader> headers = new ArrayList<>();

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FAIL_FAST = "failFast";
  @jakarta.annotation.Nullable
  private Boolean failFast = false;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    HTTP(String.valueOf("http"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public HttpCall() { 
  }

  public HttpCall paramsSchema(@jakarta.annotation.Nonnull String paramsSchema) {
    this.paramsSchema = paramsSchema;
    return this;
  }

  /**
   * JSON schema of the parameters this tool expects.
   * @return paramsSchema
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PARAMS_SCHEMA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getParamsSchema() {
    return paramsSchema;
  }


  @JsonProperty(value = JSON_PROPERTY_PARAMS_SCHEMA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParamsSchema(@jakarta.annotation.Nonnull String paramsSchema) {
    this.paramsSchema = paramsSchema;
  }


  public HttpCall url(@jakarta.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * The URL to call. Can contain ${ENV_VAR} and {{inputName}} placeholders.
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }


  public HttpCall method(@jakarta.annotation.Nonnull MethodEnum method) {
    this.method = method;
    return this;
  }

  /**
   * Get method
   * @return method
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MethodEnum getMethod() {
    return method;
  }


  @JsonProperty(value = JSON_PROPERTY_METHOD, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMethod(@jakarta.annotation.Nonnull MethodEnum method) {
    this.method = method;
  }


  public HttpCall headers(@jakarta.annotation.Nullable List<HttpHeader> headers) {
    this.headers = headers;
    return this;
  }

  public HttpCall addHeadersItem(HttpHeader headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<>();
    }
    this.headers.add(headersItem);
    return this;
  }

  /**
   * The headers to send with the HTTP request. Can contain ${ENV_VAR} and {{inputName}} placeholders.
   * @return headers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<HttpHeader> getHeaders() {
    return headers;
  }


  @JsonProperty(value = JSON_PROPERTY_HEADERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeaders(@jakarta.annotation.Nullable List<HttpHeader> headers) {
    this.headers = headers;
  }


  public HttpCall name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The tool’s name.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public HttpCall description(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * The tool’s description.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public HttpCall failFast(@jakarta.annotation.Nullable Boolean failFast) {
    this.failFast = failFast;
    return this;
  }

  /**
   * Whether to stop processing if a tool call fails.
   * @return failFast
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAIL_FAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getFailFast() {
    return failFast;
  }


  @JsonProperty(value = JSON_PROPERTY_FAIL_FAST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFailFast(@jakarta.annotation.Nullable Boolean failFast) {
    this.failFast = failFast;
  }


  public HttpCall type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  /**
   * Return true if this HttpCall object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HttpCall httpCall = (HttpCall) o;
    return Objects.equals(this.paramsSchema, httpCall.paramsSchema) &&
        Objects.equals(this.url, httpCall.url) &&
        Objects.equals(this.method, httpCall.method) &&
        Objects.equals(this.headers, httpCall.headers) &&
        Objects.equals(this.name, httpCall.name) &&
        equalsNullable(this.description, httpCall.description) &&
        Objects.equals(this.failFast, httpCall.failFast) &&
        Objects.equals(this.type, httpCall.type);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(paramsSchema, url, method, headers, name, hashCodeNullable(description), failFast, type);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HttpCall {\n");
    sb.append("    paramsSchema: ").append(toIndentedString(paramsSchema)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    failFast: ").append(toIndentedString(failFast)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `paramsSchema` to the URL query string
    if (getParamsSchema() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparamsSchema%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParamsSchema()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `method` to the URL query string
    if (getMethod() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smethod%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMethod()))));
    }

    // add `headers` to the URL query string
    if (getHeaders() != null) {
      for (int i = 0; i < getHeaders().size(); i++) {
        if (getHeaders().get(i) != null) {
          joiner.add(getHeaders().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sheaders%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `failFast` to the URL query string
    if (getFailFast() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfailFast%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFailFast()))));
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    return joiner.toString();
  }
}

