/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.KnowledgeBaseStatus;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Webhook payload for finished knowledge bases.
 */
@JsonPropertyOrder({
  KnowledgeBaseFinished.JSON_PROPERTY_ID,
  KnowledgeBaseFinished.JSON_PROPERTY_STATUS,
  KnowledgeBaseFinished.JSON_PROPERTY_DOCUMENT_COUNT,
  KnowledgeBaseFinished.JSON_PROPERTY_CHUNK_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class KnowledgeBaseFinished {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private KnowledgeBaseStatus status;

  public static final String JSON_PROPERTY_DOCUMENT_COUNT = "documentCount";
  @jakarta.annotation.Nonnull
  private Integer documentCount;

  public static final String JSON_PROPERTY_CHUNK_COUNT = "chunkCount";
  @jakarta.annotation.Nonnull
  private Integer chunkCount;

  public KnowledgeBaseFinished() { 
  }

  public KnowledgeBaseFinished id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Knowledge base ID
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public KnowledgeBaseFinished status(@jakarta.annotation.Nonnull KnowledgeBaseStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Knowledge base status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public KnowledgeBaseStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull KnowledgeBaseStatus status) {
    this.status = status;
  }


  public KnowledgeBaseFinished documentCount(@jakarta.annotation.Nonnull Integer documentCount) {
    this.documentCount = documentCount;
    return this;
  }

  /**
   * Total document count
   * @return documentCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOCUMENT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDocumentCount() {
    return documentCount;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocumentCount(@jakarta.annotation.Nonnull Integer documentCount) {
    this.documentCount = documentCount;
  }


  public KnowledgeBaseFinished chunkCount(@jakarta.annotation.Nonnull Integer chunkCount) {
    this.chunkCount = chunkCount;
    return this;
  }

  /**
   * Total chunk count
   * @return chunkCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHUNK_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getChunkCount() {
    return chunkCount;
  }


  @JsonProperty(value = JSON_PROPERTY_CHUNK_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChunkCount(@jakarta.annotation.Nonnull Integer chunkCount) {
    this.chunkCount = chunkCount;
  }


  /**
   * Return true if this KnowledgeBaseFinished object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KnowledgeBaseFinished knowledgeBaseFinished = (KnowledgeBaseFinished) o;
    return Objects.equals(this.id, knowledgeBaseFinished.id) &&
        Objects.equals(this.status, knowledgeBaseFinished.status) &&
        Objects.equals(this.documentCount, knowledgeBaseFinished.documentCount) &&
        Objects.equals(this.chunkCount, knowledgeBaseFinished.chunkCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, documentCount, chunkCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KnowledgeBaseFinished {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    documentCount: ").append(toIndentedString(documentCount)).append("\n");
    sb.append("    chunkCount: ").append(toIndentedString(chunkCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `documentCount` to the URL query string
    if (getDocumentCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdocumentCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDocumentCount()))));
    }

    // add `chunkCount` to the URL query string
    if (getChunkCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schunkCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChunkCount()))));
    }

    return joiner.toString();
  }
}

