/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.KnowledgeBaseStatus;
import com.promptjuggler.client.model.KnowledgeDocumentSummary;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Knowledge base with documents
 */
@JsonPropertyOrder({
  KnowledgeBaseResponse.JSON_PROPERTY_ID,
  KnowledgeBaseResponse.JSON_PROPERTY_STATUS,
  KnowledgeBaseResponse.JSON_PROPERTY_DOCUMENT_COUNT,
  KnowledgeBaseResponse.JSON_PROPERTY_CHUNK_COUNT,
  KnowledgeBaseResponse.JSON_PROPERTY_DOCUMENTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class KnowledgeBaseResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private KnowledgeBaseStatus status;

  public static final String JSON_PROPERTY_DOCUMENT_COUNT = "documentCount";
  @jakarta.annotation.Nonnull
  private Integer documentCount;

  public static final String JSON_PROPERTY_CHUNK_COUNT = "chunkCount";
  @jakarta.annotation.Nonnull
  private Integer chunkCount;

  public static final String JSON_PROPERTY_DOCUMENTS = "documents";
  @jakarta.annotation.Nonnull
  private List<KnowledgeDocumentSummary> documents = new ArrayList<>();

  public KnowledgeBaseResponse() { 
  }

  public KnowledgeBaseResponse id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Knowledge base ID
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public KnowledgeBaseResponse status(@jakarta.annotation.Nonnull KnowledgeBaseStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Processing status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public KnowledgeBaseStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull KnowledgeBaseStatus status) {
    this.status = status;
  }


  public KnowledgeBaseResponse documentCount(@jakarta.annotation.Nonnull Integer documentCount) {
    this.documentCount = documentCount;
    return this;
  }

  /**
   * Total number of documents
   * @return documentCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOCUMENT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDocumentCount() {
    return documentCount;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENT_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocumentCount(@jakarta.annotation.Nonnull Integer documentCount) {
    this.documentCount = documentCount;
  }


  public KnowledgeBaseResponse chunkCount(@jakarta.annotation.Nonnull Integer chunkCount) {
    this.chunkCount = chunkCount;
    return this;
  }

  /**
   * Total number of chunks across all documents
   * @return chunkCount
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CHUNK_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getChunkCount() {
    return chunkCount;
  }


  @JsonProperty(value = JSON_PROPERTY_CHUNK_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChunkCount(@jakarta.annotation.Nonnull Integer chunkCount) {
    this.chunkCount = chunkCount;
  }


  public KnowledgeBaseResponse documents(@jakarta.annotation.Nonnull List<KnowledgeDocumentSummary> documents) {
    this.documents = documents;
    return this;
  }

  public KnowledgeBaseResponse addDocumentsItem(KnowledgeDocumentSummary documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

  /**
   * Get documents
   * @return documents
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<KnowledgeDocumentSummary> getDocuments() {
    return documents;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocuments(@jakarta.annotation.Nonnull List<KnowledgeDocumentSummary> documents) {
    this.documents = documents;
  }


  /**
   * Return true if this KnowledgeBaseResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KnowledgeBaseResponse knowledgeBaseResponse = (KnowledgeBaseResponse) o;
    return Objects.equals(this.id, knowledgeBaseResponse.id) &&
        Objects.equals(this.status, knowledgeBaseResponse.status) &&
        Objects.equals(this.documentCount, knowledgeBaseResponse.documentCount) &&
        Objects.equals(this.chunkCount, knowledgeBaseResponse.chunkCount) &&
        Objects.equals(this.documents, knowledgeBaseResponse.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, documentCount, chunkCount, documents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KnowledgeBaseResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    documentCount: ").append(toIndentedString(documentCount)).append("\n");
    sb.append("    chunkCount: ").append(toIndentedString(chunkCount)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `documentCount` to the URL query string
    if (getDocumentCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdocumentCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDocumentCount()))));
    }

    // add `chunkCount` to the URL query string
    if (getChunkCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%schunkCount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getChunkCount()))));
    }

    // add `documents` to the URL query string
    if (getDocuments() != null) {
      for (int i = 0; i < getDocuments().size(); i++) {
        if (getDocuments().get(i) != null) {
          joiner.add(getDocuments().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sdocuments%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

