/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.KnowledgeDocumentStatus;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Knowledge document summary (without counts)
 */
@JsonPropertyOrder({
  KnowledgeDocumentSummary.JSON_PROPERTY_ID,
  KnowledgeDocumentSummary.JSON_PROPERTY_STATUS,
  KnowledgeDocumentSummary.JSON_PROPERTY_FILE_NAME,
  KnowledgeDocumentSummary.JSON_PROPERTY_BYTES,
  KnowledgeDocumentSummary.JSON_PROPERTY_MIME_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class KnowledgeDocumentSummary {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private KnowledgeDocumentStatus status;

  public static final String JSON_PROPERTY_FILE_NAME = "fileName";
  @jakarta.annotation.Nonnull
  private String fileName;

  public static final String JSON_PROPERTY_BYTES = "bytes";
  @jakarta.annotation.Nonnull
  private Integer bytes;

  public static final String JSON_PROPERTY_MIME_TYPE = "mimeType";
  @jakarta.annotation.Nonnull
  private String mimeType;

  public KnowledgeDocumentSummary() { 
  }

  public KnowledgeDocumentSummary id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Document ID
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public KnowledgeDocumentSummary status(@jakarta.annotation.Nonnull KnowledgeDocumentStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Processing status
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public KnowledgeDocumentStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull KnowledgeDocumentStatus status) {
    this.status = status;
  }


  public KnowledgeDocumentSummary fileName(@jakarta.annotation.Nonnull String fileName) {
    this.fileName = fileName;
    return this;
  }

  /**
   * Original file name
   * @return fileName
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFileName() {
    return fileName;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFileName(@jakarta.annotation.Nonnull String fileName) {
    this.fileName = fileName;
  }


  public KnowledgeDocumentSummary bytes(@jakarta.annotation.Nonnull Integer bytes) {
    this.bytes = bytes;
    return this;
  }

  /**
   * File size in bytes
   * @return bytes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BYTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getBytes() {
    return bytes;
  }


  @JsonProperty(value = JSON_PROPERTY_BYTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBytes(@jakarta.annotation.Nonnull Integer bytes) {
    this.bytes = bytes;
  }


  public KnowledgeDocumentSummary mimeType(@jakarta.annotation.Nonnull String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  /**
   * MIME type
   * @return mimeType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMimeType() {
    return mimeType;
  }


  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMimeType(@jakarta.annotation.Nonnull String mimeType) {
    this.mimeType = mimeType;
  }


  /**
   * Return true if this KnowledgeDocumentSummary object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KnowledgeDocumentSummary knowledgeDocumentSummary = (KnowledgeDocumentSummary) o;
    return Objects.equals(this.id, knowledgeDocumentSummary.id) &&
        Objects.equals(this.status, knowledgeDocumentSummary.status) &&
        Objects.equals(this.fileName, knowledgeDocumentSummary.fileName) &&
        Objects.equals(this.bytes, knowledgeDocumentSummary.bytes) &&
        Objects.equals(this.mimeType, knowledgeDocumentSummary.mimeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, fileName, bytes, mimeType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KnowledgeDocumentSummary {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    bytes: ").append(toIndentedString(bytes)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `fileName` to the URL query string
    if (getFileName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfileName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFileName()))));
    }

    // add `bytes` to the URL query string
    if (getBytes() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbytes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBytes()))));
    }

    // add `mimeType` to the URL query string
    if (getMimeType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smimeType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMimeType()))));
    }

    return joiner.toString();
  }
}

