/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Built-in MCP server tool.
 */
@JsonPropertyOrder({
  Mcp.JSON_PROPERTY_NAME,
  Mcp.JSON_PROPERTY_URL,
  Mcp.JSON_PROPERTY_AUTHORIZATION_TOKEN,
  Mcp.JSON_PROPERTY_ALLOWED_TOOLS,
  Mcp.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class Mcp {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_URL = "url";
  @jakarta.annotation.Nonnull
  private String url;

  public static final String JSON_PROPERTY_AUTHORIZATION_TOKEN = "authorizationToken";
  private JsonNullable<String> authorizationToken = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ALLOWED_TOOLS = "allowedTools";
  private JsonNullable<List<String>> allowedTools = JsonNullable.<List<String>>undefined();

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    MCP(String.valueOf("mcp"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public Mcp() { 
  }

  public Mcp name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * The MCP server tool’s name.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public Mcp url(@jakarta.annotation.Nonnull String url) {
    this.url = url;
    return this;
  }

  /**
   * The URL of the MCP server.
   * @return url
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUrl(@jakarta.annotation.Nonnull String url) {
    this.url = url;
  }


  public Mcp authorizationToken(@jakarta.annotation.Nullable String authorizationToken) {
    this.authorizationToken = JsonNullable.<String>of(authorizationToken);
    return this;
  }

  /**
   * Authorization token for the MCP server.
   * @return authorizationToken
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getAuthorizationToken() {
        return authorizationToken.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_AUTHORIZATION_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAuthorizationToken_JsonNullable() {
    return authorizationToken;
  }
  
  @JsonProperty(JSON_PROPERTY_AUTHORIZATION_TOKEN)
  public void setAuthorizationToken_JsonNullable(JsonNullable<String> authorizationToken) {
    this.authorizationToken = authorizationToken;
  }

  public void setAuthorizationToken(@jakarta.annotation.Nullable String authorizationToken) {
    this.authorizationToken = JsonNullable.<String>of(authorizationToken);
  }


  public Mcp allowedTools(@jakarta.annotation.Nullable List<String> allowedTools) {
    this.allowedTools = JsonNullable.<List<String>>of(allowedTools);
    return this;
  }

  public Mcp addAllowedToolsItem(String allowedToolsItem) {
    if (this.allowedTools == null || !this.allowedTools.isPresent()) {
      this.allowedTools = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.allowedTools.get().add(allowedToolsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Tool names the model may call. Empty or omitted allows all of the server’s tools.
   * @return allowedTools
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public List<String> getAllowedTools() {
        return allowedTools.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ALLOWED_TOOLS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getAllowedTools_JsonNullable() {
    return allowedTools;
  }
  
  @JsonProperty(JSON_PROPERTY_ALLOWED_TOOLS)
  public void setAllowedTools_JsonNullable(JsonNullable<List<String>> allowedTools) {
    this.allowedTools = allowedTools;
  }

  public void setAllowedTools(@jakarta.annotation.Nullable List<String> allowedTools) {
    this.allowedTools = JsonNullable.<List<String>>of(allowedTools);
  }


  public Mcp type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  /**
   * Return true if this Mcp object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mcp mcp = (Mcp) o;
    return Objects.equals(this.name, mcp.name) &&
        Objects.equals(this.url, mcp.url) &&
        equalsNullable(this.authorizationToken, mcp.authorizationToken) &&
        equalsNullable(this.allowedTools, mcp.allowedTools) &&
        Objects.equals(this.type, mcp.type);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, url, hashCodeNullable(authorizationToken), hashCodeNullable(allowedTools), type);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mcp {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    authorizationToken: ").append(toIndentedString(authorizationToken)).append("\n");
    sb.append("    allowedTools: ").append(toIndentedString(allowedTools)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `authorizationToken` to the URL query string
    if (getAuthorizationToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sauthorizationToken%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAuthorizationToken()))));
    }

    // add `allowedTools` to the URL query string
    if (getAllowedTools() != null) {
      for (int i = 0; i < getAllowedTools().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sallowedTools%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAllowedTools().get(i)))));
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    return joiner.toString();
  }
}

