/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets Model
 */
public enum Model {
  
  GPT_5_5("gpt-5.5"),
  
  GPT_5_5_PRO("gpt-5.5-pro"),
  
  GPT_5_4("gpt-5.4"),
  
  GPT_5_4_MINI("gpt-5.4-mini"),
  
  GPT_5_4_NANO("gpt-5.4-nano"),
  
  GPT_5_4_PRO("gpt-5.4-pro"),
  
  GPT_5_2("gpt-5.2"),
  
  GPT_5_2_PRO("gpt-5.2-pro"),
  
  GPT_5_1("gpt-5.1"),
  
  GPT_4_1("gpt-4.1"),
  
  GPT_4_1_MINI("gpt-4.1-mini"),
  
  O1_MINI("o1-mini"),
  
  GPT_4O("gpt-4o"),
  
  GPT_4O_MINI("gpt-4o-mini"),
  
  GEMINI_3_1_PRO_PREVIEW("gemini-3.1-pro-preview"),
  
  GEMINI_3_FLASH_PREVIEW("gemini-3-flash-preview"),
  
  GEMINI_2_5_PRO("gemini-2.5-pro"),
  
  GEMINI_2_5_FLASH("gemini-2.5-flash"),
  
  GEMINI_2_5_FLASH_LITE("gemini-2.5-flash-lite"),
  
  GEMINI_2_0_FLASH("gemini-2.0-flash"),
  
  GEMINI_2_0_FLASH_LITE("gemini-2.0-flash-lite"),
  
  CLAUDE_OPUS_4_8("claude-opus-4-8"),
  
  CLAUDE_OPUS_4_7("claude-opus-4-7"),
  
  CLAUDE_OPUS_4_6("claude-opus-4-6"),
  
  CLAUDE_OPUS_4_5("claude-opus-4-5"),
  
  CLAUDE_SONNET_4_6("claude-sonnet-4-6"),
  
  CLAUDE_SONNET_4_5("claude-sonnet-4-5"),
  
  CLAUDE_HAIKU_4_5("claude-haiku-4-5");

  private String value;

  Model(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static Model fromValue(String value) {
    for (Model b : Model.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    if (prefix == null) {
      prefix = "";
    }

    return String.format(java.util.Locale.ROOT, "%s=%s", prefix, this.toString());
  }

}

