/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.ServiceTier;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * AI model parameters.
 */
@JsonPropertyOrder({
  ModelParams.JSON_PROPERTY_MAX_COMPLETION_TOKENS,
  ModelParams.JSON_PROPERTY_TEMPERATURE,
  ModelParams.JSON_PROPERTY_TOP_P,
  ModelParams.JSON_PROPERTY_VERBOSITY,
  ModelParams.JSON_PROPERTY_REASONING_EFFORT,
  ModelParams.JSON_PROPERTY_REASONING_SUMMARY,
  ModelParams.JSON_PROPERTY_SERVICE_TIER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelParams {
  public static final String JSON_PROPERTY_MAX_COMPLETION_TOKENS = "maxCompletionTokens";
  private JsonNullable<Integer> maxCompletionTokens = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_TEMPERATURE = "temperature";
  private JsonNullable<Float> temperature = JsonNullable.<Float>undefined();

  public static final String JSON_PROPERTY_TOP_P = "topP";
  private JsonNullable<Float> topP = JsonNullable.<Float>undefined();

  /**
   * Verbosity.
   */
  public enum VerbosityEnum {
    LOW(String.valueOf("low")),
    
    MEDIUM(String.valueOf("medium")),
    
    HIGH(String.valueOf("high"));

    private String value;

    VerbosityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VerbosityEnum fromValue(String value) {
      for (VerbosityEnum b : VerbosityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_VERBOSITY = "verbosity";
  private JsonNullable<VerbosityEnum> verbosity = JsonNullable.<VerbosityEnum>undefined();

  /**
   * Reasoning effort.
   */
  public enum ReasoningEffortEnum {
    NONE(String.valueOf("none")),
    
    LOW(String.valueOf("low")),
    
    MEDIUM(String.valueOf("medium")),
    
    HIGH(String.valueOf("high")),
    
    XHIGH(String.valueOf("xhigh")),
    
    MAX(String.valueOf("max"));

    private String value;

    ReasoningEffortEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ReasoningEffortEnum fromValue(String value) {
      for (ReasoningEffortEnum b : ReasoningEffortEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_REASONING_EFFORT = "reasoningEffort";
  private JsonNullable<ReasoningEffortEnum> reasoningEffort = JsonNullable.<ReasoningEffortEnum>undefined();

  public static final String JSON_PROPERTY_REASONING_SUMMARY = "reasoningSummary";
  private JsonNullable<Boolean> reasoningSummary = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_SERVICE_TIER = "serviceTier";
  private JsonNullable<ServiceTier> serviceTier = JsonNullable.<ServiceTier>undefined();

  public ModelParams() { 
  }

  public ModelParams maxCompletionTokens(@jakarta.annotation.Nullable Integer maxCompletionTokens) {
    this.maxCompletionTokens = JsonNullable.<Integer>of(maxCompletionTokens);
    return this;
  }

  /**
   * Maximum completion tokens.
   * minimum: 1
   * @return maxCompletionTokens
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Integer getMaxCompletionTokens() {
        return maxCompletionTokens.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_MAX_COMPLETION_TOKENS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getMaxCompletionTokens_JsonNullable() {
    return maxCompletionTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_MAX_COMPLETION_TOKENS)
  public void setMaxCompletionTokens_JsonNullable(JsonNullable<Integer> maxCompletionTokens) {
    this.maxCompletionTokens = maxCompletionTokens;
  }

  public void setMaxCompletionTokens(@jakarta.annotation.Nullable Integer maxCompletionTokens) {
    this.maxCompletionTokens = JsonNullable.<Integer>of(maxCompletionTokens);
  }


  public ModelParams temperature(@jakarta.annotation.Nullable Float temperature) {
    this.temperature = JsonNullable.<Float>of(temperature);
    return this;
  }

  /**
   * Temperature.
   * minimum: 0
   * maximum: 2
   * @return temperature
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Float getTemperature() {
        return temperature.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TEMPERATURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Float> getTemperature_JsonNullable() {
    return temperature;
  }
  
  @JsonProperty(JSON_PROPERTY_TEMPERATURE)
  public void setTemperature_JsonNullable(JsonNullable<Float> temperature) {
    this.temperature = temperature;
  }

  public void setTemperature(@jakarta.annotation.Nullable Float temperature) {
    this.temperature = JsonNullable.<Float>of(temperature);
  }


  public ModelParams topP(@jakarta.annotation.Nullable Float topP) {
    this.topP = JsonNullable.<Float>of(topP);
    return this;
  }

  /**
   * Top P.
   * minimum: 0
   * maximum: 2
   * @return topP
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Float getTopP() {
        return topP.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_TOP_P, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Float> getTopP_JsonNullable() {
    return topP;
  }
  
  @JsonProperty(JSON_PROPERTY_TOP_P)
  public void setTopP_JsonNullable(JsonNullable<Float> topP) {
    this.topP = topP;
  }

  public void setTopP(@jakarta.annotation.Nullable Float topP) {
    this.topP = JsonNullable.<Float>of(topP);
  }


  public ModelParams verbosity(@jakarta.annotation.Nullable VerbosityEnum verbosity) {
    this.verbosity = JsonNullable.<VerbosityEnum>of(verbosity);
    return this;
  }

  /**
   * Verbosity.
   * @return verbosity
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public VerbosityEnum getVerbosity() {
        return verbosity.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_VERBOSITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<VerbosityEnum> getVerbosity_JsonNullable() {
    return verbosity;
  }
  
  @JsonProperty(JSON_PROPERTY_VERBOSITY)
  public void setVerbosity_JsonNullable(JsonNullable<VerbosityEnum> verbosity) {
    this.verbosity = verbosity;
  }

  public void setVerbosity(@jakarta.annotation.Nullable VerbosityEnum verbosity) {
    this.verbosity = JsonNullable.<VerbosityEnum>of(verbosity);
  }


  public ModelParams reasoningEffort(@jakarta.annotation.Nullable ReasoningEffortEnum reasoningEffort) {
    this.reasoningEffort = JsonNullable.<ReasoningEffortEnum>of(reasoningEffort);
    return this;
  }

  /**
   * Reasoning effort.
   * @return reasoningEffort
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public ReasoningEffortEnum getReasoningEffort() {
        return reasoningEffort.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REASONING_EFFORT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ReasoningEffortEnum> getReasoningEffort_JsonNullable() {
    return reasoningEffort;
  }
  
  @JsonProperty(JSON_PROPERTY_REASONING_EFFORT)
  public void setReasoningEffort_JsonNullable(JsonNullable<ReasoningEffortEnum> reasoningEffort) {
    this.reasoningEffort = reasoningEffort;
  }

  public void setReasoningEffort(@jakarta.annotation.Nullable ReasoningEffortEnum reasoningEffort) {
    this.reasoningEffort = JsonNullable.<ReasoningEffortEnum>of(reasoningEffort);
  }


  public ModelParams reasoningSummary(@jakarta.annotation.Nullable Boolean reasoningSummary) {
    this.reasoningSummary = JsonNullable.<Boolean>of(reasoningSummary);
    return this;
  }

  /**
   * Return reasoning summary.
   * @return reasoningSummary
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Boolean getReasoningSummary() {
        return reasoningSummary.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REASONING_SUMMARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getReasoningSummary_JsonNullable() {
    return reasoningSummary;
  }
  
  @JsonProperty(JSON_PROPERTY_REASONING_SUMMARY)
  public void setReasoningSummary_JsonNullable(JsonNullable<Boolean> reasoningSummary) {
    this.reasoningSummary = reasoningSummary;
  }

  public void setReasoningSummary(@jakarta.annotation.Nullable Boolean reasoningSummary) {
    this.reasoningSummary = JsonNullable.<Boolean>of(reasoningSummary);
  }


  public ModelParams serviceTier(@jakarta.annotation.Nullable ServiceTier serviceTier) {
    this.serviceTier = JsonNullable.<ServiceTier>of(serviceTier);
    return this;
  }

  /**
   * Service tier.
   * @return serviceTier
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public ServiceTier getServiceTier() {
        return serviceTier.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SERVICE_TIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<ServiceTier> getServiceTier_JsonNullable() {
    return serviceTier;
  }
  
  @JsonProperty(JSON_PROPERTY_SERVICE_TIER)
  public void setServiceTier_JsonNullable(JsonNullable<ServiceTier> serviceTier) {
    this.serviceTier = serviceTier;
  }

  public void setServiceTier(@jakarta.annotation.Nullable ServiceTier serviceTier) {
    this.serviceTier = JsonNullable.<ServiceTier>of(serviceTier);
  }


  /**
   * Return true if this ModelParams object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelParams modelParams = (ModelParams) o;
    return equalsNullable(this.maxCompletionTokens, modelParams.maxCompletionTokens) &&
        equalsNullable(this.temperature, modelParams.temperature) &&
        equalsNullable(this.topP, modelParams.topP) &&
        equalsNullable(this.verbosity, modelParams.verbosity) &&
        equalsNullable(this.reasoningEffort, modelParams.reasoningEffort) &&
        equalsNullable(this.reasoningSummary, modelParams.reasoningSummary) &&
        equalsNullable(this.serviceTier, modelParams.serviceTier);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(maxCompletionTokens), hashCodeNullable(temperature), hashCodeNullable(topP), hashCodeNullable(verbosity), hashCodeNullable(reasoningEffort), hashCodeNullable(reasoningSummary), hashCodeNullable(serviceTier));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelParams {\n");
    sb.append("    maxCompletionTokens: ").append(toIndentedString(maxCompletionTokens)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    topP: ").append(toIndentedString(topP)).append("\n");
    sb.append("    verbosity: ").append(toIndentedString(verbosity)).append("\n");
    sb.append("    reasoningEffort: ").append(toIndentedString(reasoningEffort)).append("\n");
    sb.append("    reasoningSummary: ").append(toIndentedString(reasoningSummary)).append("\n");
    sb.append("    serviceTier: ").append(toIndentedString(serviceTier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `maxCompletionTokens` to the URL query string
    if (getMaxCompletionTokens() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smaxCompletionTokens%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMaxCompletionTokens()))));
    }

    // add `temperature` to the URL query string
    if (getTemperature() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stemperature%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTemperature()))));
    }

    // add `topP` to the URL query string
    if (getTopP() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stopP%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTopP()))));
    }

    // add `verbosity` to the URL query string
    if (getVerbosity() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sverbosity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerbosity()))));
    }

    // add `reasoningEffort` to the URL query string
    if (getReasoningEffort() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreasoningEffort%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReasoningEffort()))));
    }

    // add `reasoningSummary` to the URL query string
    if (getReasoningSummary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreasoningSummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReasoningSummary()))));
    }

    // add `serviceTier` to the URL query string
    if (getServiceTier() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sserviceTier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceTier()))));
    }

    return joiner.toString();
  }
}

