/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * ModelCost
 */
@JsonPropertyOrder({
  ModelCost.JSON_PROPERTY_INPUT,
  ModelCost.JSON_PROPERTY_CACHED_INPUT,
  ModelCost.JSON_PROPERTY_OUTPUT,
  ModelCost.JSON_PROPERTY_WEB_SEARCH,
  ModelCost.JSON_PROPERTY_TOTAL
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class ModelCost {
  public static final String JSON_PROPERTY_INPUT = "input";
  @jakarta.annotation.Nonnull
  private Float input;

  public static final String JSON_PROPERTY_CACHED_INPUT = "cachedInput";
  private JsonNullable<Float> cachedInput = JsonNullable.<Float>undefined();

  public static final String JSON_PROPERTY_OUTPUT = "output";
  @jakarta.annotation.Nonnull
  private Float output;

  public static final String JSON_PROPERTY_WEB_SEARCH = "webSearch";
  @jakarta.annotation.Nullable
  private Float webSearch = 0f;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @jakarta.annotation.Nonnull
  private Float total;

  public ModelCost() { 
  }

  public ModelCost input(@jakarta.annotation.Nonnull Float input) {
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getInput() {
    return input;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInput(@jakarta.annotation.Nonnull Float input) {
    this.input = input;
  }


  public ModelCost cachedInput(@jakarta.annotation.Nullable Float cachedInput) {
    this.cachedInput = JsonNullable.<Float>of(cachedInput);
    return this;
  }

  /**
   * Get cachedInput
   * @return cachedInput
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Float getCachedInput() {
        return cachedInput.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_CACHED_INPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Float> getCachedInput_JsonNullable() {
    return cachedInput;
  }
  
  @JsonProperty(JSON_PROPERTY_CACHED_INPUT)
  public void setCachedInput_JsonNullable(JsonNullable<Float> cachedInput) {
    this.cachedInput = cachedInput;
  }

  public void setCachedInput(@jakarta.annotation.Nullable Float cachedInput) {
    this.cachedInput = JsonNullable.<Float>of(cachedInput);
  }


  public ModelCost output(@jakarta.annotation.Nonnull Float output) {
    this.output = output;
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getOutput() {
    return output;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutput(@jakarta.annotation.Nonnull Float output) {
    this.output = output;
  }


  public ModelCost webSearch(@jakarta.annotation.Nullable Float webSearch) {
    this.webSearch = webSearch;
    return this;
  }

  /**
   * Get webSearch
   * @return webSearch
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WEB_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Float getWebSearch() {
    return webSearch;
  }


  @JsonProperty(value = JSON_PROPERTY_WEB_SEARCH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebSearch(@jakarta.annotation.Nullable Float webSearch) {
    this.webSearch = webSearch;
  }


  public ModelCost total(@jakarta.annotation.Nonnull Float total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Float getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@jakarta.annotation.Nonnull Float total) {
    this.total = total;
  }


  /**
   * Return true if this ModelCost object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelCost modelCost = (ModelCost) o;
    return Objects.equals(this.input, modelCost.input) &&
        equalsNullable(this.cachedInput, modelCost.cachedInput) &&
        Objects.equals(this.output, modelCost.output) &&
        Objects.equals(this.webSearch, modelCost.webSearch) &&
        Objects.equals(this.total, modelCost.total);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, hashCodeNullable(cachedInput), output, webSearch, total);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelCost {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    cachedInput: ").append(toIndentedString(cachedInput)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    webSearch: ").append(toIndentedString(webSearch)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `input` to the URL query string
    if (getInput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInput()))));
    }

    // add `cachedInput` to the URL query string
    if (getCachedInput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scachedInput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCachedInput()))));
    }

    // add `output` to the URL query string
    if (getOutput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soutput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOutput()))));
    }

    // add `webSearch` to the URL query string
    if (getWebSearch() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%swebSearch%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebSearch()))));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    return joiner.toString();
  }
}

