/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.ContentMessageResponse;
import com.promptjuggler.client.model.Memory;
import com.promptjuggler.client.model.Model;
import com.promptjuggler.client.model.ModelParams;
import com.promptjuggler.client.model.Provider;
import com.promptjuggler.client.model.ResponseFormat;
import com.promptjuggler.client.model.Tool;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Prompt revision
 */
@JsonPropertyOrder({
  PromptRevision.JSON_PROPERTY_ID,
  PromptRevision.JSON_PROPERTY_PROMPT_ID,
  PromptRevision.JSON_PROPERTY_MEMORY,
  PromptRevision.JSON_PROPERTY_PROVIDER,
  PromptRevision.JSON_PROPERTY_MODEL,
  PromptRevision.JSON_PROPERTY_MODEL_PARAMS,
  PromptRevision.JSON_PROPERTY_RESPONSE_FORMAT,
  PromptRevision.JSON_PROPERTY_SYSTEM_INSTRUCTION,
  PromptRevision.JSON_PROPERTY_MESSAGES,
  PromptRevision.JSON_PROPERTY_TOOLS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class PromptRevision {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_PROMPT_ID = "promptId";
  @jakarta.annotation.Nonnull
  private UUID promptId;

  public static final String JSON_PROPERTY_MEMORY = "memory";
  @jakarta.annotation.Nonnull
  private Memory memory;

  public static final String JSON_PROPERTY_PROVIDER = "provider";
  @jakarta.annotation.Nonnull
  private Provider provider;

  public static final String JSON_PROPERTY_MODEL = "model";
  @jakarta.annotation.Nonnull
  private Model model;

  public static final String JSON_PROPERTY_MODEL_PARAMS = "modelParams";
  @jakarta.annotation.Nonnull
  private ModelParams modelParams;

  public static final String JSON_PROPERTY_RESPONSE_FORMAT = "responseFormat";
  @jakarta.annotation.Nonnull
  private ResponseFormat responseFormat;

  public static final String JSON_PROPERTY_SYSTEM_INSTRUCTION = "systemInstruction";
  private JsonNullable<String> systemInstruction = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_MESSAGES = "messages";
  @jakarta.annotation.Nonnull
  private List<ContentMessageResponse> messages = new ArrayList<>();

  public static final String JSON_PROPERTY_TOOLS = "tools";
  @jakarta.annotation.Nonnull
  private List<Tool> tools = new ArrayList<>();

  public PromptRevision() { 
  }

  public PromptRevision id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Prompt revision ID.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public PromptRevision promptId(@jakarta.annotation.Nonnull UUID promptId) {
    this.promptId = promptId;
    return this;
  }

  /**
   * Prompt ID.
   * @return promptId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROMPT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getPromptId() {
    return promptId;
  }


  @JsonProperty(value = JSON_PROPERTY_PROMPT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPromptId(@jakarta.annotation.Nonnull UUID promptId) {
    this.promptId = promptId;
  }


  public PromptRevision memory(@jakarta.annotation.Nonnull Memory memory) {
    this.memory = memory;
    return this;
  }

  /**
   * Memory mode.
   * @return memory
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MEMORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Memory getMemory() {
    return memory;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMORY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMemory(@jakarta.annotation.Nonnull Memory memory) {
    this.memory = memory;
  }


  public PromptRevision provider(@jakarta.annotation.Nonnull Provider provider) {
    this.provider = provider;
    return this;
  }

  /**
   * AI provider.
   * @return provider
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Provider getProvider() {
    return provider;
  }


  @JsonProperty(value = JSON_PROPERTY_PROVIDER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvider(@jakarta.annotation.Nonnull Provider provider) {
    this.provider = provider;
  }


  public PromptRevision model(@jakarta.annotation.Nonnull Model model) {
    this.model = model;
    return this;
  }

  /**
   * AI model.
   * @return model
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Model getModel() {
    return model;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModel(@jakarta.annotation.Nonnull Model model) {
    this.model = model;
  }


  public PromptRevision modelParams(@jakarta.annotation.Nonnull ModelParams modelParams) {
    this.modelParams = modelParams;
    return this;
  }

  /**
   * Model parameters.
   * @return modelParams
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODEL_PARAMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ModelParams getModelParams() {
    return modelParams;
  }


  @JsonProperty(value = JSON_PROPERTY_MODEL_PARAMS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setModelParams(@jakarta.annotation.Nonnull ModelParams modelParams) {
    this.modelParams = modelParams;
  }


  public PromptRevision responseFormat(@jakarta.annotation.Nonnull ResponseFormat responseFormat) {
    this.responseFormat = responseFormat;
    return this;
  }

  /**
   * AI model response format.
   * @return responseFormat
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RESPONSE_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ResponseFormat getResponseFormat() {
    return responseFormat;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSE_FORMAT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponseFormat(@jakarta.annotation.Nonnull ResponseFormat responseFormat) {
    this.responseFormat = responseFormat;
  }


  public PromptRevision systemInstruction(@jakarta.annotation.Nullable String systemInstruction) {
    this.systemInstruction = JsonNullable.<String>of(systemInstruction);
    return this;
  }

  /**
   * The system prompt.
   * @return systemInstruction
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getSystemInstruction() {
        return systemInstruction.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_SYSTEM_INSTRUCTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getSystemInstruction_JsonNullable() {
    return systemInstruction;
  }
  
  @JsonProperty(JSON_PROPERTY_SYSTEM_INSTRUCTION)
  public void setSystemInstruction_JsonNullable(JsonNullable<String> systemInstruction) {
    this.systemInstruction = systemInstruction;
  }

  public void setSystemInstruction(@jakarta.annotation.Nullable String systemInstruction) {
    this.systemInstruction = JsonNullable.<String>of(systemInstruction);
  }


  public PromptRevision messages(@jakarta.annotation.Nonnull List<ContentMessageResponse> messages) {
    this.messages = messages;
    return this;
  }

  public PromptRevision addMessagesItem(ContentMessageResponse messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<>();
    }
    this.messages.add(messagesItem);
    return this;
  }

  /**
   * User and assistant messages.
   * @return messages
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ContentMessageResponse> getMessages() {
    return messages;
  }


  @JsonProperty(value = JSON_PROPERTY_MESSAGES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessages(@jakarta.annotation.Nonnull List<ContentMessageResponse> messages) {
    this.messages = messages;
  }


  public PromptRevision tools(@jakarta.annotation.Nonnull List<Tool> tools) {
    this.tools = tools;
    return this;
  }

  public PromptRevision addToolsItem(Tool toolsItem) {
    if (this.tools == null) {
      this.tools = new ArrayList<>();
    }
    this.tools.add(toolsItem);
    return this;
  }

  /**
   * Available tools.
   * @return tools
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Tool> getTools() {
    return tools;
  }


  @JsonProperty(value = JSON_PROPERTY_TOOLS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTools(@jakarta.annotation.Nonnull List<Tool> tools) {
    this.tools = tools;
  }


  /**
   * Return true if this PromptRevision object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptRevision promptRevision = (PromptRevision) o;
    return Objects.equals(this.id, promptRevision.id) &&
        Objects.equals(this.promptId, promptRevision.promptId) &&
        Objects.equals(this.memory, promptRevision.memory) &&
        Objects.equals(this.provider, promptRevision.provider) &&
        Objects.equals(this.model, promptRevision.model) &&
        Objects.equals(this.modelParams, promptRevision.modelParams) &&
        Objects.equals(this.responseFormat, promptRevision.responseFormat) &&
        equalsNullable(this.systemInstruction, promptRevision.systemInstruction) &&
        Objects.equals(this.messages, promptRevision.messages) &&
        Objects.equals(this.tools, promptRevision.tools);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, promptId, memory, provider, model, modelParams, responseFormat, hashCodeNullable(systemInstruction), messages, tools);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptRevision {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    promptId: ").append(toIndentedString(promptId)).append("\n");
    sb.append("    memory: ").append(toIndentedString(memory)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    modelParams: ").append(toIndentedString(modelParams)).append("\n");
    sb.append("    responseFormat: ").append(toIndentedString(responseFormat)).append("\n");
    sb.append("    systemInstruction: ").append(toIndentedString(systemInstruction)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    tools: ").append(toIndentedString(tools)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `promptId` to the URL query string
    if (getPromptId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spromptId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPromptId()))));
    }

    // add `memory` to the URL query string
    if (getMemory() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smemory%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMemory()))));
    }

    // add `provider` to the URL query string
    if (getProvider() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprovider%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProvider()))));
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smodel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getModel()))));
    }

    // add `modelParams` to the URL query string
    if (getModelParams() != null) {
      joiner.add(getModelParams().toUrlQueryString(prefix + "modelParams" + suffix));
    }

    // add `responseFormat` to the URL query string
    if (getResponseFormat() != null) {
      joiner.add(getResponseFormat().toUrlQueryString(prefix + "responseFormat" + suffix));
    }

    // add `systemInstruction` to the URL query string
    if (getSystemInstruction() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssystemInstruction%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSystemInstruction()))));
    }

    // add `messages` to the URL query string
    if (getMessages() != null) {
      for (int i = 0; i < getMessages().size(); i++) {
        if (getMessages().get(i) != null) {
          joiner.add(getMessages().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%smessages%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `tools` to the URL query string
    if (getTools() != null) {
      for (int i = 0; i < getTools().size(); i++) {
        if (getTools().get(i) != null) {
          joiner.add(getTools().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%stools%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

