/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.RunStatus;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Prompt run status and result.
 */
@JsonPropertyOrder({
  PromptRun.JSON_PROPERTY_ID,
  PromptRun.JSON_PROPERTY_STATUS,
  PromptRun.JSON_PROPERTY_CREATED_AT,
  PromptRun.JSON_PROPERTY_FINISHED_AT,
  PromptRun.JSON_PROPERTY_OUTPUT,
  PromptRun.JSON_PROPERTY_ERROR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class PromptRun {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private RunStatus status;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_FINISHED_AT = "finishedAt";
  private JsonNullable<OffsetDateTime> finishedAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_OUTPUT = "output";
  private JsonNullable<String> output = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ERROR = "error";
  private JsonNullable<String> error = JsonNullable.<String>undefined();

  public PromptRun() { 
  }

  public PromptRun id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Prompt run ID.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public PromptRun status(@jakarta.annotation.Nonnull RunStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Current run status.
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RunStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull RunStatus status) {
    this.status = status;
  }


  public PromptRun createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Timestamp when the run was created.
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public PromptRun finishedAt(@jakarta.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = JsonNullable.<OffsetDateTime>of(finishedAt);
    return this;
  }

  /**
   * Timestamp when the run finished. Null while the run is pending.
   * @return finishedAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getFinishedAt() {
        return finishedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FINISHED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getFinishedAt_JsonNullable() {
    return finishedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  public void setFinishedAt_JsonNullable(JsonNullable<OffsetDateTime> finishedAt) {
    this.finishedAt = finishedAt;
  }

  public void setFinishedAt(@jakarta.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = JsonNullable.<OffsetDateTime>of(finishedAt);
  }


  public PromptRun output(@jakarta.annotation.Nullable String output) {
    this.output = JsonNullable.<String>of(output);
    return this;
  }

  /**
   * LLM output text. Null while pending or when the run failed.
   * @return output
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getOutput() {
        return output.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOutput_JsonNullable() {
    return output;
  }
  
  @JsonProperty(JSON_PROPERTY_OUTPUT)
  public void setOutput_JsonNullable(JsonNullable<String> output) {
    this.output = output;
  }

  public void setOutput(@jakarta.annotation.Nullable String output) {
    this.output = JsonNullable.<String>of(output);
  }


  public PromptRun error(@jakarta.annotation.Nullable String error) {
    this.error = JsonNullable.<String>of(error);
    return this;
  }

  /**
   * Error message if the run failed. Null on success.
   * @return error
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public String getError() {
        return error.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getError_JsonNullable() {
    return error;
  }
  
  @JsonProperty(JSON_PROPERTY_ERROR)
  public void setError_JsonNullable(JsonNullable<String> error) {
    this.error = error;
  }

  public void setError(@jakarta.annotation.Nullable String error) {
    this.error = JsonNullable.<String>of(error);
  }


  /**
   * Return true if this PromptRun object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromptRun promptRun = (PromptRun) o;
    return Objects.equals(this.id, promptRun.id) &&
        Objects.equals(this.status, promptRun.status) &&
        Objects.equals(this.createdAt, promptRun.createdAt) &&
        equalsNullable(this.finishedAt, promptRun.finishedAt) &&
        equalsNullable(this.output, promptRun.output) &&
        equalsNullable(this.error, promptRun.error);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, createdAt, hashCodeNullable(finishedAt), hashCodeNullable(output), hashCodeNullable(error));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromptRun {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `finishedAt` to the URL query string
    if (getFinishedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfinishedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFinishedAt()))));
    }

    // add `output` to the URL query string
    if (getOutput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soutput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOutput()))));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%serror%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getError()))));
    }

    return joiner.toString();
  }
}

