/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.JsonObjectFormat;
import com.promptjuggler.client.model.JsonSchemaFormat;
import com.promptjuggler.client.model.TextFormat;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.promptjuggler.client.ApiClient;
import com.promptjuggler.client.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
@JsonDeserialize(using = ResponseFormat.ResponseFormatDeserializer.class)
@JsonSerialize(using = ResponseFormat.ResponseFormatSerializer.class)
public class ResponseFormat extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(ResponseFormat.class.getName());

    public static class ResponseFormatSerializer extends StdSerializer<ResponseFormat> {
        public ResponseFormatSerializer(Class<ResponseFormat> t) {
            super(t);
        }

        public ResponseFormatSerializer() {
            this(null);
        }

        @Override
        public void serialize(ResponseFormat value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class ResponseFormatDeserializer extends StdDeserializer<ResponseFormat> {
        public ResponseFormatDeserializer() {
            this(ResponseFormat.class);
        }

        public ResponseFormatDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public ResponseFormat deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize JsonObjectFormat
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (JsonObjectFormat.class.equals(Integer.class) || JsonObjectFormat.class.equals(Long.class) || JsonObjectFormat.class.equals(Float.class) || JsonObjectFormat.class.equals(Double.class) || JsonObjectFormat.class.equals(Boolean.class) || JsonObjectFormat.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((JsonObjectFormat.class.equals(Integer.class) || JsonObjectFormat.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((JsonObjectFormat.class.equals(Float.class) || JsonObjectFormat.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (JsonObjectFormat.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (JsonObjectFormat.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(JsonObjectFormat.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'JsonObjectFormat'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'JsonObjectFormat'", e);
            }

            // deserialize JsonSchemaFormat
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (JsonSchemaFormat.class.equals(Integer.class) || JsonSchemaFormat.class.equals(Long.class) || JsonSchemaFormat.class.equals(Float.class) || JsonSchemaFormat.class.equals(Double.class) || JsonSchemaFormat.class.equals(Boolean.class) || JsonSchemaFormat.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((JsonSchemaFormat.class.equals(Integer.class) || JsonSchemaFormat.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((JsonSchemaFormat.class.equals(Float.class) || JsonSchemaFormat.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (JsonSchemaFormat.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (JsonSchemaFormat.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(JsonSchemaFormat.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'JsonSchemaFormat'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'JsonSchemaFormat'", e);
            }

            // deserialize TextFormat
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (TextFormat.class.equals(Integer.class) || TextFormat.class.equals(Long.class) || TextFormat.class.equals(Float.class) || TextFormat.class.equals(Double.class) || TextFormat.class.equals(Boolean.class) || TextFormat.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((TextFormat.class.equals(Integer.class) || TextFormat.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((TextFormat.class.equals(Float.class) || TextFormat.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (TextFormat.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (TextFormat.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(TextFormat.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'TextFormat'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'TextFormat'", e);
            }

            if (match == 1) {
                ResponseFormat ret = new ResponseFormat();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for ResponseFormat: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public ResponseFormat getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "ResponseFormat cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public ResponseFormat() {
        super("oneOf", Boolean.FALSE);
    }

    public ResponseFormat(JsonObjectFormat o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ResponseFormat(JsonSchemaFormat o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public ResponseFormat(TextFormat o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("JsonObjectFormat", JsonObjectFormat.class);
        schemas.put("JsonSchemaFormat", JsonSchemaFormat.class);
        schemas.put("TextFormat", TextFormat.class);
        JSON.registerDescendants(ResponseFormat.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("json_object", JsonObjectFormat.class);
        mappings.put("json_schema", JsonSchemaFormat.class);
        mappings.put("text", TextFormat.class);
        mappings.put("ResponseFormat", ResponseFormat.class);
        JSON.registerDiscriminator(ResponseFormat.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return ResponseFormat.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * JsonObjectFormat, JsonSchemaFormat, TextFormat
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(JsonObjectFormat.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(JsonSchemaFormat.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(TextFormat.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be JsonObjectFormat, JsonSchemaFormat, TextFormat");
    }

    /**
     * Get the actual instance, which can be the following:
     * JsonObjectFormat, JsonSchemaFormat, TextFormat
     *
     * @return The actual instance (JsonObjectFormat, JsonSchemaFormat, TextFormat)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `JsonObjectFormat`. If the actual instance is not `JsonObjectFormat`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `JsonObjectFormat`
     * @throws ClassCastException if the instance is not `JsonObjectFormat`
     */
    public JsonObjectFormat getJsonObjectFormat() throws ClassCastException {
        return (JsonObjectFormat)super.getActualInstance();
    }

    /**
     * Get the actual instance of `JsonSchemaFormat`. If the actual instance is not `JsonSchemaFormat`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `JsonSchemaFormat`
     * @throws ClassCastException if the instance is not `JsonSchemaFormat`
     */
    public JsonSchemaFormat getJsonSchemaFormat() throws ClassCastException {
        return (JsonSchemaFormat)super.getActualInstance();
    }

    /**
     * Get the actual instance of `TextFormat`. If the actual instance is not `TextFormat`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TextFormat`
     * @throws ClassCastException if the instance is not `TextFormat`
     */
    public TextFormat getTextFormat() throws ClassCastException {
        return (TextFormat)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof TextFormat) {
        if (getActualInstance() != null) {
          joiner.add(((TextFormat)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof JsonObjectFormat) {
        if (getActualInstance() != null) {
          joiner.add(((JsonObjectFormat)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof JsonSchemaFormat) {
        if (getActualInstance() != null) {
          joiner.add(((JsonSchemaFormat)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

