/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.ServiceTier;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * TokenUsage
 */
@JsonPropertyOrder({
  TokenUsage.JSON_PROPERTY_INPUT,
  TokenUsage.JSON_PROPERTY_INPUT_CACHED,
  TokenUsage.JSON_PROPERTY_OUTPUT,
  TokenUsage.JSON_PROPERTY_REASONING,
  TokenUsage.JSON_PROPERTY_TOTAL,
  TokenUsage.JSON_PROPERTY_SERVICE_TIER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TokenUsage {
  public static final String JSON_PROPERTY_INPUT = "input";
  @jakarta.annotation.Nonnull
  private Integer input;

  public static final String JSON_PROPERTY_INPUT_CACHED = "inputCached";
  @jakarta.annotation.Nonnull
  private Integer inputCached;

  public static final String JSON_PROPERTY_OUTPUT = "output";
  @jakarta.annotation.Nonnull
  private Integer output;

  public static final String JSON_PROPERTY_REASONING = "reasoning";
  @jakarta.annotation.Nonnull
  private Integer reasoning;

  public static final String JSON_PROPERTY_TOTAL = "total";
  @jakarta.annotation.Nonnull
  private Integer total;

  public static final String JSON_PROPERTY_SERVICE_TIER = "serviceTier";
  @jakarta.annotation.Nullable
  private ServiceTier serviceTier;

  public TokenUsage() { 
  }

  public TokenUsage input(@jakarta.annotation.Nonnull Integer input) {
    this.input = input;
    return this;
  }

  /**
   * Get input
   * @return input
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getInput() {
    return input;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInput(@jakarta.annotation.Nonnull Integer input) {
    this.input = input;
  }


  public TokenUsage inputCached(@jakarta.annotation.Nonnull Integer inputCached) {
    this.inputCached = inputCached;
    return this;
  }

  /**
   * Get inputCached
   * @return inputCached
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INPUT_CACHED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getInputCached() {
    return inputCached;
  }


  @JsonProperty(value = JSON_PROPERTY_INPUT_CACHED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInputCached(@jakarta.annotation.Nonnull Integer inputCached) {
    this.inputCached = inputCached;
  }


  public TokenUsage output(@jakarta.annotation.Nonnull Integer output) {
    this.output = output;
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getOutput() {
    return output;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOutput(@jakarta.annotation.Nonnull Integer output) {
    this.output = output;
  }


  public TokenUsage reasoning(@jakarta.annotation.Nonnull Integer reasoning) {
    this.reasoning = reasoning;
    return this;
  }

  /**
   * Get reasoning
   * @return reasoning
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REASONING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getReasoning() {
    return reasoning;
  }


  @JsonProperty(value = JSON_PROPERTY_REASONING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReasoning(@jakarta.annotation.Nonnull Integer reasoning) {
    this.reasoning = reasoning;
  }


  public TokenUsage total(@jakarta.annotation.Nonnull Integer total) {
    this.total = total;
    return this;
  }

  /**
   * Get total
   * @return total
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getTotal() {
    return total;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotal(@jakarta.annotation.Nonnull Integer total) {
    this.total = total;
  }


  public TokenUsage serviceTier(@jakarta.annotation.Nullable ServiceTier serviceTier) {
    this.serviceTier = serviceTier;
    return this;
  }

  /**
   * Get serviceTier
   * @return serviceTier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_TIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ServiceTier getServiceTier() {
    return serviceTier;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_TIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceTier(@jakarta.annotation.Nullable ServiceTier serviceTier) {
    this.serviceTier = serviceTier;
  }


  /**
   * Return true if this TokenUsage object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TokenUsage tokenUsage = (TokenUsage) o;
    return Objects.equals(this.input, tokenUsage.input) &&
        Objects.equals(this.inputCached, tokenUsage.inputCached) &&
        Objects.equals(this.output, tokenUsage.output) &&
        Objects.equals(this.reasoning, tokenUsage.reasoning) &&
        Objects.equals(this.total, tokenUsage.total) &&
        Objects.equals(this.serviceTier, tokenUsage.serviceTier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(input, inputCached, output, reasoning, total, serviceTier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TokenUsage {\n");
    sb.append("    input: ").append(toIndentedString(input)).append("\n");
    sb.append("    inputCached: ").append(toIndentedString(inputCached)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("    reasoning: ").append(toIndentedString(reasoning)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    serviceTier: ").append(toIndentedString(serviceTier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `input` to the URL query string
    if (getInput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInput()))));
    }

    // add `inputCached` to the URL query string
    if (getInputCached() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sinputCached%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInputCached()))));
    }

    // add `output` to the URL query string
    if (getOutput() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%soutput%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOutput()))));
    }

    // add `reasoning` to the URL query string
    if (getReasoning() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreasoning%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReasoning()))));
    }

    // add `total` to the URL query string
    if (getTotal() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stotal%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotal()))));
    }

    // add `serviceTier` to the URL query string
    if (getServiceTier() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sserviceTier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceTier()))));
    }

    return joiner.toString();
  }
}

