/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.HttpCall;
import com.promptjuggler.client.model.HttpHeader;
import com.promptjuggler.client.model.KnowledgeSearch;
import com.promptjuggler.client.model.Mcp;
import com.promptjuggler.client.model.PromptCall;
import com.promptjuggler.client.model.ScriptCall;
import com.promptjuggler.client.model.VersionRef;
import com.promptjuggler.client.model.WebSearch;
import com.promptjuggler.client.model.WorkflowCall;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.promptjuggler.client.ApiClient;
import com.promptjuggler.client.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
@JsonDeserialize(using = Tool.ToolDeserializer.class)
@JsonSerialize(using = Tool.ToolSerializer.class)
public class Tool extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(Tool.class.getName());

    public static class ToolSerializer extends StdSerializer<Tool> {
        public ToolSerializer(Class<Tool> t) {
            super(t);
        }

        public ToolSerializer() {
            this(null);
        }

        @Override
        public void serialize(Tool value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class ToolDeserializer extends StdDeserializer<Tool> {
        public ToolDeserializer() {
            this(Tool.class);
        }

        public ToolDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public Tool deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize HttpCall
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (HttpCall.class.equals(Integer.class) || HttpCall.class.equals(Long.class) || HttpCall.class.equals(Float.class) || HttpCall.class.equals(Double.class) || HttpCall.class.equals(Boolean.class) || HttpCall.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((HttpCall.class.equals(Integer.class) || HttpCall.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((HttpCall.class.equals(Float.class) || HttpCall.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (HttpCall.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (HttpCall.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(HttpCall.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'HttpCall'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'HttpCall'", e);
            }

            // deserialize KnowledgeSearch
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (KnowledgeSearch.class.equals(Integer.class) || KnowledgeSearch.class.equals(Long.class) || KnowledgeSearch.class.equals(Float.class) || KnowledgeSearch.class.equals(Double.class) || KnowledgeSearch.class.equals(Boolean.class) || KnowledgeSearch.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((KnowledgeSearch.class.equals(Integer.class) || KnowledgeSearch.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((KnowledgeSearch.class.equals(Float.class) || KnowledgeSearch.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (KnowledgeSearch.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (KnowledgeSearch.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(KnowledgeSearch.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'KnowledgeSearch'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'KnowledgeSearch'", e);
            }

            // deserialize Mcp
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (Mcp.class.equals(Integer.class) || Mcp.class.equals(Long.class) || Mcp.class.equals(Float.class) || Mcp.class.equals(Double.class) || Mcp.class.equals(Boolean.class) || Mcp.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((Mcp.class.equals(Integer.class) || Mcp.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((Mcp.class.equals(Float.class) || Mcp.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (Mcp.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (Mcp.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(Mcp.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'Mcp'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'Mcp'", e);
            }

            // deserialize PromptCall
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (PromptCall.class.equals(Integer.class) || PromptCall.class.equals(Long.class) || PromptCall.class.equals(Float.class) || PromptCall.class.equals(Double.class) || PromptCall.class.equals(Boolean.class) || PromptCall.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((PromptCall.class.equals(Integer.class) || PromptCall.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((PromptCall.class.equals(Float.class) || PromptCall.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (PromptCall.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (PromptCall.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(PromptCall.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'PromptCall'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'PromptCall'", e);
            }

            // deserialize ScriptCall
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (ScriptCall.class.equals(Integer.class) || ScriptCall.class.equals(Long.class) || ScriptCall.class.equals(Float.class) || ScriptCall.class.equals(Double.class) || ScriptCall.class.equals(Boolean.class) || ScriptCall.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((ScriptCall.class.equals(Integer.class) || ScriptCall.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((ScriptCall.class.equals(Float.class) || ScriptCall.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (ScriptCall.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (ScriptCall.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(ScriptCall.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'ScriptCall'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'ScriptCall'", e);
            }

            // deserialize WebSearch
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WebSearch.class.equals(Integer.class) || WebSearch.class.equals(Long.class) || WebSearch.class.equals(Float.class) || WebSearch.class.equals(Double.class) || WebSearch.class.equals(Boolean.class) || WebSearch.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WebSearch.class.equals(Integer.class) || WebSearch.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WebSearch.class.equals(Float.class) || WebSearch.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WebSearch.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WebSearch.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WebSearch.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WebSearch'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WebSearch'", e);
            }

            // deserialize WorkflowCall
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (WorkflowCall.class.equals(Integer.class) || WorkflowCall.class.equals(Long.class) || WorkflowCall.class.equals(Float.class) || WorkflowCall.class.equals(Double.class) || WorkflowCall.class.equals(Boolean.class) || WorkflowCall.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((WorkflowCall.class.equals(Integer.class) || WorkflowCall.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((WorkflowCall.class.equals(Float.class) || WorkflowCall.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (WorkflowCall.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (WorkflowCall.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(WorkflowCall.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'WorkflowCall'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'WorkflowCall'", e);
            }

            if (match == 1) {
                Tool ret = new Tool();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for Tool: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public Tool getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "Tool cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public Tool() {
        super("oneOf", Boolean.FALSE);
    }

    public Tool(HttpCall o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Tool(KnowledgeSearch o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Tool(Mcp o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Tool(PromptCall o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Tool(ScriptCall o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Tool(WebSearch o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public Tool(WorkflowCall o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("HttpCall", HttpCall.class);
        schemas.put("KnowledgeSearch", KnowledgeSearch.class);
        schemas.put("Mcp", Mcp.class);
        schemas.put("PromptCall", PromptCall.class);
        schemas.put("ScriptCall", ScriptCall.class);
        schemas.put("WebSearch", WebSearch.class);
        schemas.put("WorkflowCall", WorkflowCall.class);
        JSON.registerDescendants(Tool.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("http", HttpCall.class);
        mappings.put("knowledge_search", KnowledgeSearch.class);
        mappings.put("mcp", Mcp.class);
        mappings.put("prompt", PromptCall.class);
        mappings.put("script", ScriptCall.class);
        mappings.put("web_search", WebSearch.class);
        mappings.put("workflow", WorkflowCall.class);
        mappings.put("Tool", Tool.class);
        JSON.registerDiscriminator(Tool.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return Tool.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(HttpCall.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(KnowledgeSearch.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(Mcp.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(PromptCall.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(ScriptCall.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(WebSearch.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(WorkflowCall.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall");
    }

    /**
     * Get the actual instance, which can be the following:
     * HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall
     *
     * @return The actual instance (HttpCall, KnowledgeSearch, Mcp, PromptCall, ScriptCall, WebSearch, WorkflowCall)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `HttpCall`. If the actual instance is not `HttpCall`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `HttpCall`
     * @throws ClassCastException if the instance is not `HttpCall`
     */
    public HttpCall getHttpCall() throws ClassCastException {
        return (HttpCall)super.getActualInstance();
    }

    /**
     * Get the actual instance of `KnowledgeSearch`. If the actual instance is not `KnowledgeSearch`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `KnowledgeSearch`
     * @throws ClassCastException if the instance is not `KnowledgeSearch`
     */
    public KnowledgeSearch getKnowledgeSearch() throws ClassCastException {
        return (KnowledgeSearch)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Mcp`. If the actual instance is not `Mcp`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Mcp`
     * @throws ClassCastException if the instance is not `Mcp`
     */
    public Mcp getMcp() throws ClassCastException {
        return (Mcp)super.getActualInstance();
    }

    /**
     * Get the actual instance of `PromptCall`. If the actual instance is not `PromptCall`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PromptCall`
     * @throws ClassCastException if the instance is not `PromptCall`
     */
    public PromptCall getPromptCall() throws ClassCastException {
        return (PromptCall)super.getActualInstance();
    }

    /**
     * Get the actual instance of `ScriptCall`. If the actual instance is not `ScriptCall`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ScriptCall`
     * @throws ClassCastException if the instance is not `ScriptCall`
     */
    public ScriptCall getScriptCall() throws ClassCastException {
        return (ScriptCall)super.getActualInstance();
    }

    /**
     * Get the actual instance of `WebSearch`. If the actual instance is not `WebSearch`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WebSearch`
     * @throws ClassCastException if the instance is not `WebSearch`
     */
    public WebSearch getWebSearch() throws ClassCastException {
        return (WebSearch)super.getActualInstance();
    }

    /**
     * Get the actual instance of `WorkflowCall`. If the actual instance is not `WorkflowCall`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `WorkflowCall`
     * @throws ClassCastException if the instance is not `WorkflowCall`
     */
    public WorkflowCall getWorkflowCall() throws ClassCastException {
        return (WorkflowCall)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof WebSearch) {
        if (getActualInstance() != null) {
          joiner.add(((WebSearch)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof HttpCall) {
        if (getActualInstance() != null) {
          joiner.add(((HttpCall)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof ScriptCall) {
        if (getActualInstance() != null) {
          joiner.add(((ScriptCall)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof Mcp) {
        if (getActualInstance() != null) {
          joiner.add(((Mcp)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof PromptCall) {
        if (getActualInstance() != null) {
          joiner.add(((PromptCall)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof WorkflowCall) {
        if (getActualInstance() != null) {
          joiner.add(((WorkflowCall)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof KnowledgeSearch) {
        if (getActualInstance() != null) {
          joiner.add(((KnowledgeSearch)getActualInstance()).toUrlQueryString(prefix + "one_of_6" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

