/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.Citation;
import com.promptjuggler.client.model.ToolStatus;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * A tool the model used: its name and how the call ended.
 */
@JsonPropertyOrder({
  TranscriptTool.JSON_PROPERTY_NAME,
  TranscriptTool.JSON_PROPERTY_STATUS,
  TranscriptTool.JSON_PROPERTY_QUERIES,
  TranscriptTool.JSON_PROPERTY_CITATIONS,
  TranscriptTool.JSON_PROPERTY_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class TranscriptTool {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private ToolStatus status;

  public static final String JSON_PROPERTY_QUERIES = "queries";
  @jakarta.annotation.Nonnull
  private List<String> queries = new ArrayList<>();

  public static final String JSON_PROPERTY_CITATIONS = "citations";
  @jakarta.annotation.Nonnull
  private List<Citation> citations = new ArrayList<>();

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    TOOL(String.valueOf("tool")),
    
    UNKNOWN_DEFAULT_OPEN_API(String.valueOf("unknown_default_open_api"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  public TranscriptTool() { 
  }

  public TranscriptTool name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Tool name, as the model called it.
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public TranscriptTool status(@jakarta.annotation.Nonnull ToolStatus status) {
    this.status = status;
    return this;
  }

  /**
   * How the call ended.
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ToolStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull ToolStatus status) {
    this.status = status;
  }


  public TranscriptTool queries(@jakarta.annotation.Nonnull List<String> queries) {
    this.queries = queries;
    return this;
  }

  public TranscriptTool addQueriesItem(String queriesItem) {
    if (this.queries == null) {
      this.queries = new ArrayList<>();
    }
    this.queries.add(queriesItem);
    return this;
  }

  /**
   * Search queries the model ran. Only ever populated by the built-in web_search tool.
   * @return queries
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getQueries() {
    return queries;
  }


  @JsonProperty(value = JSON_PROPERTY_QUERIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueries(@jakarta.annotation.Nonnull List<String> queries) {
    this.queries = queries;
  }


  public TranscriptTool citations(@jakarta.annotation.Nonnull List<Citation> citations) {
    this.citations = citations;
    return this;
  }

  public TranscriptTool addCitationsItem(Citation citationsItem) {
    if (this.citations == null) {
      this.citations = new ArrayList<>();
    }
    this.citations.add(citationsItem);
    return this;
  }

  /**
   * Sources this call returned. Only ever populated by the built-in web_search tool.
   * @return citations
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CITATIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Citation> getCitations() {
    return citations;
  }


  @JsonProperty(value = JSON_PROPERTY_CITATIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCitations(@jakarta.annotation.Nonnull List<Citation> citations) {
    this.citations = citations;
  }


  public TranscriptTool type(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }


  /**
   * Return true if this TranscriptTool object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TranscriptTool transcriptTool = (TranscriptTool) o;
    return Objects.equals(this.name, transcriptTool.name) &&
        Objects.equals(this.status, transcriptTool.status) &&
        Objects.equals(this.queries, transcriptTool.queries) &&
        Objects.equals(this.citations, transcriptTool.citations) &&
        Objects.equals(this.type, transcriptTool.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, queries, citations, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TranscriptTool {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    queries: ").append(toIndentedString(queries)).append("\n");
    sb.append("    citations: ").append(toIndentedString(citations)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `queries` to the URL query string
    if (getQueries() != null) {
      for (int i = 0; i < getQueries().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%squeries%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getQueries().get(i)))));
      }
    }

    // add `citations` to the URL query string
    if (getCitations() != null) {
      for (int i = 0; i < getCitations().size(); i++) {
        if (getCitations().get(i) != null) {
          joiner.add(getCitations().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%scitations%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stype%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getType()))));
    }

    return joiner.toString();
  }
}

