/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.Citation;
import com.promptjuggler.client.model.ToolStatus;
import com.promptjuggler.client.model.TranscriptData;
import com.promptjuggler.client.model.TranscriptText;
import com.promptjuggler.client.model.TranscriptTool;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.promptjuggler.client.ApiClient;
import com.promptjuggler.client.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
@JsonDeserialize(using = TranscriptItem.TranscriptItemDeserializer.class)
@JsonSerialize(using = TranscriptItem.TranscriptItemSerializer.class)
public class TranscriptItem extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(TranscriptItem.class.getName());

    public static class TranscriptItemSerializer extends StdSerializer<TranscriptItem> {
        public TranscriptItemSerializer(Class<TranscriptItem> t) {
            super(t);
        }

        public TranscriptItemSerializer() {
            this(null);
        }

        @Override
        public void serialize(TranscriptItem value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class TranscriptItemDeserializer extends StdDeserializer<TranscriptItem> {
        public TranscriptItemDeserializer() {
            this(TranscriptItem.class);
        }

        public TranscriptItemDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public TranscriptItem deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = ctxt.readTree(jp);
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize TranscriptData
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (TranscriptData.class.equals(Integer.class) || TranscriptData.class.equals(Long.class) || TranscriptData.class.equals(Float.class) || TranscriptData.class.equals(Double.class) || TranscriptData.class.equals(Boolean.class) || TranscriptData.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((TranscriptData.class.equals(Integer.class) || TranscriptData.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((TranscriptData.class.equals(Float.class) || TranscriptData.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (TranscriptData.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (TranscriptData.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(TranscriptData.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'TranscriptData'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'TranscriptData'", e);
            }

            // deserialize TranscriptText
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (TranscriptText.class.equals(Integer.class) || TranscriptText.class.equals(Long.class) || TranscriptText.class.equals(Float.class) || TranscriptText.class.equals(Double.class) || TranscriptText.class.equals(Boolean.class) || TranscriptText.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((TranscriptText.class.equals(Integer.class) || TranscriptText.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((TranscriptText.class.equals(Float.class) || TranscriptText.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (TranscriptText.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (TranscriptText.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(TranscriptText.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'TranscriptText'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'TranscriptText'", e);
            }

            // deserialize TranscriptTool
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (TranscriptTool.class.equals(Integer.class) || TranscriptTool.class.equals(Long.class) || TranscriptTool.class.equals(Float.class) || TranscriptTool.class.equals(Double.class) || TranscriptTool.class.equals(Boolean.class) || TranscriptTool.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((TranscriptTool.class.equals(Integer.class) || TranscriptTool.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((TranscriptTool.class.equals(Float.class) || TranscriptTool.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (TranscriptTool.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (TranscriptTool.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(TranscriptTool.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'TranscriptTool'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'TranscriptTool'", e);
            }

            if (match == 1) {
                TranscriptItem ret = new TranscriptItem();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for TranscriptItem: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public TranscriptItem getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "TranscriptItem cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public TranscriptItem() {
        super("oneOf", Boolean.FALSE);
    }

    public TranscriptItem(TranscriptData o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public TranscriptItem(TranscriptText o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public TranscriptItem(TranscriptTool o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("TranscriptData", TranscriptData.class);
        schemas.put("TranscriptText", TranscriptText.class);
        schemas.put("TranscriptTool", TranscriptTool.class);
        JSON.registerDescendants(TranscriptItem.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("data", TranscriptData.class);
        mappings.put("text", TranscriptText.class);
        mappings.put("tool", TranscriptTool.class);
        mappings.put("TranscriptItem", TranscriptItem.class);
        JSON.registerDiscriminator(TranscriptItem.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return TranscriptItem.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * TranscriptData, TranscriptText, TranscriptTool
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(TranscriptData.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(TranscriptText.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(TranscriptTool.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be TranscriptData, TranscriptText, TranscriptTool");
    }

    /**
     * Get the actual instance, which can be the following:
     * TranscriptData, TranscriptText, TranscriptTool
     *
     * @return The actual instance (TranscriptData, TranscriptText, TranscriptTool)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `TranscriptData`. If the actual instance is not `TranscriptData`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TranscriptData`
     * @throws ClassCastException if the instance is not `TranscriptData`
     */
    public TranscriptData getTranscriptData() throws ClassCastException {
        return (TranscriptData)super.getActualInstance();
    }

    /**
     * Get the actual instance of `TranscriptText`. If the actual instance is not `TranscriptText`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TranscriptText`
     * @throws ClassCastException if the instance is not `TranscriptText`
     */
    public TranscriptText getTranscriptText() throws ClassCastException {
        return (TranscriptText)super.getActualInstance();
    }

    /**
     * Get the actual instance of `TranscriptTool`. If the actual instance is not `TranscriptTool`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `TranscriptTool`
     * @throws ClassCastException if the instance is not `TranscriptTool`
     */
    public TranscriptTool getTranscriptTool() throws ClassCastException {
        return (TranscriptTool)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof TranscriptText) {
        if (getActualInstance() != null) {
          joiner.add(((TranscriptText)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof TranscriptTool) {
        if (getActualInstance() != null) {
          joiner.add(((TranscriptTool)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof TranscriptData) {
        if (getActualInstance() != null) {
          joiner.add(((TranscriptData)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

