/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * A reference to a revision.
 */
@JsonPropertyOrder({
  VersionRef.JSON_PROPERTY_DEFINITION_ID,
  VersionRef.JSON_PROPERTY_PARENT_ID,
  VersionRef.JSON_PROPERTY_ID_OR_TAG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class VersionRef {
  public static final String JSON_PROPERTY_DEFINITION_ID = "definitionId";
  @jakarta.annotation.Nonnull
  private UUID definitionId;

  public static final String JSON_PROPERTY_PARENT_ID = "parentId";
  private JsonNullable<UUID> parentId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_ID_OR_TAG = "idOrTag";
  @jakarta.annotation.Nonnull
  private String idOrTag;

  public VersionRef() { 
  }

  public VersionRef definitionId(@jakarta.annotation.Nonnull UUID definitionId) {
    this.definitionId = definitionId;
    return this;
  }

  /**
   * Definition – prompt or workflow – ID.
   * @return definitionId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DEFINITION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getDefinitionId() {
    return definitionId;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFINITION_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDefinitionId(@jakarta.annotation.Nonnull UUID definitionId) {
    this.definitionId = definitionId;
  }


  public VersionRef parentId(@jakarta.annotation.Nullable UUID parentId) {
    this.parentId = JsonNullable.<UUID>of(parentId);
    return this;
  }

  /**
   * Deprecated alias of definitionId.
   * @return parentId
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public UUID getParentId() {
        return parentId.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getParentId_JsonNullable() {
    return parentId;
  }
  
  @JsonProperty(JSON_PROPERTY_PARENT_ID)
  public void setParentId_JsonNullable(JsonNullable<UUID> parentId) {
    this.parentId = parentId;
  }

  public void setParentId(@jakarta.annotation.Nullable UUID parentId) {
    this.parentId = JsonNullable.<UUID>of(parentId);
  }


  public VersionRef idOrTag(@jakarta.annotation.Nonnull String idOrTag) {
    this.idOrTag = idOrTag;
    return this;
  }

  /**
   * Revision ID or version number or tag.
   * @return idOrTag
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID_OR_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getIdOrTag() {
    return idOrTag;
  }


  @JsonProperty(value = JSON_PROPERTY_ID_OR_TAG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdOrTag(@jakarta.annotation.Nonnull String idOrTag) {
    this.idOrTag = idOrTag;
  }


  /**
   * Return true if this VersionRef object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VersionRef versionRef = (VersionRef) o;
    return Objects.equals(this.definitionId, versionRef.definitionId) &&
        equalsNullable(this.parentId, versionRef.parentId) &&
        Objects.equals(this.idOrTag, versionRef.idOrTag);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(definitionId, hashCodeNullable(parentId), idOrTag);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VersionRef {\n");
    sb.append("    definitionId: ").append(toIndentedString(definitionId)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    idOrTag: ").append(toIndentedString(idOrTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `definitionId` to the URL query string
    if (getDefinitionId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sdefinitionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDefinitionId()))));
    }

    // add `parentId` to the URL query string
    if (getParentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparentId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParentId()))));
    }

    // add `idOrTag` to the URL query string
    if (getIdOrTag() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sidOrTag%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIdOrTag()))));
    }

    return joiner.toString();
  }
}

