/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.promptjuggler.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.promptjuggler.client.model.RunStatus;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.promptjuggler.client.ApiClient;
/**
 * Workflow run status and results.
 */
@JsonPropertyOrder({
  WorkflowRun.JSON_PROPERTY_ID,
  WorkflowRun.JSON_PROPERTY_STATUS,
  WorkflowRun.JSON_PROPERTY_CREATED_AT,
  WorkflowRun.JSON_PROPERTY_FINISHED_AT,
  WorkflowRun.JSON_PROPERTY_OUTPUTS,
  WorkflowRun.JSON_PROPERTY_ERRORS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class WorkflowRun {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private RunStatus status;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_FINISHED_AT = "finishedAt";
  private JsonNullable<OffsetDateTime> finishedAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_OUTPUTS = "outputs";
  @jakarta.annotation.Nonnull
  private Map<String, String> outputs = new HashMap<>();

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @jakarta.annotation.Nonnull
  private List<String> errors = new ArrayList<>();

  public WorkflowRun() { 
  }

  public WorkflowRun id(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Workflow run ID.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public WorkflowRun status(@jakarta.annotation.Nonnull RunStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Current run status.
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RunStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull RunStatus status) {
    this.status = status;
  }


  public WorkflowRun createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Timestamp when the run was created.
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public WorkflowRun finishedAt(@jakarta.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = JsonNullable.<OffsetDateTime>of(finishedAt);
    return this;
  }

  /**
   * Timestamp when the run finished. Null while the run is pending.
   * @return finishedAt
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getFinishedAt() {
        return finishedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_FINISHED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getFinishedAt_JsonNullable() {
    return finishedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_FINISHED_AT)
  public void setFinishedAt_JsonNullable(JsonNullable<OffsetDateTime> finishedAt) {
    this.finishedAt = finishedAt;
  }

  public void setFinishedAt(@jakarta.annotation.Nullable OffsetDateTime finishedAt) {
    this.finishedAt = JsonNullable.<OffsetDateTime>of(finishedAt);
  }


  public WorkflowRun outputs(@jakarta.annotation.Nonnull Map<String, String> outputs) {
    this.outputs = outputs;
    return this;
  }

  public WorkflowRun putOutputsItem(String key, String outputsItem) {
    if (this.outputs == null) {
      this.outputs = new HashMap<>();
    }
    this.outputs.put(key, outputsItem);
    return this;
  }

  /**
   * Map of output node names to their values. Empty object while pending.
   * @return outputs
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_OUTPUTS, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, String> getOutputs() {
    return outputs;
  }


  @JsonProperty(value = JSON_PROPERTY_OUTPUTS, required = true)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setOutputs(@jakarta.annotation.Nonnull Map<String, String> outputs) {
    this.outputs = outputs;
  }


  public WorkflowRun errors(@jakarta.annotation.Nonnull List<String> errors) {
    this.errors = errors;
    return this;
  }

  public WorkflowRun addErrorsItem(String errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * List of error messages from failed nodes. Empty array on success.
   * @return errors
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrors(@jakarta.annotation.Nonnull List<String> errors) {
    this.errors = errors;
  }


  /**
   * Return true if this WorkflowRun object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowRun workflowRun = (WorkflowRun) o;
    return Objects.equals(this.id, workflowRun.id) &&
        Objects.equals(this.status, workflowRun.status) &&
        Objects.equals(this.createdAt, workflowRun.createdAt) &&
        equalsNullable(this.finishedAt, workflowRun.finishedAt) &&
        Objects.equals(this.outputs, workflowRun.outputs) &&
        Objects.equals(this.errors, workflowRun.errors);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, createdAt, hashCodeNullable(finishedAt), outputs, errors);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowRun {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    finishedAt: ").append(toIndentedString(finishedAt)).append("\n");
    sb.append("    outputs: ").append(toIndentedString(outputs)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screatedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `finishedAt` to the URL query string
    if (getFinishedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfinishedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFinishedAt()))));
    }

    // add `outputs` to the URL query string
    if (getOutputs() != null) {
      for (String _key : getOutputs().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%soutputs%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getOutputs().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getOutputs().get(_key)))));
      }
    }

    // add `errors` to the URL query string
    if (getErrors() != null) {
      for (int i = 0; i < getErrors().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%serrors%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getErrors().get(i)))));
      }
    }

    return joiner.toString();
  }
}

