/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.promptjuggler.client.api;

import com.promptjuggler.client.ApiClient;
import com.promptjuggler.client.ApiException;
import com.promptjuggler.client.ApiResponse;
import com.promptjuggler.client.Configuration;
import com.promptjuggler.client.Pair;

import com.promptjuggler.client.model.ErrorResponse;
import java.io.File;
import com.promptjuggler.client.model.KnowledgeBaseResponse;
import com.promptjuggler.client.model.KnowledgeDocumentResponse;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class KnowledgeBasesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public KnowledgeBasesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public KnowledgeBasesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Delete a knowledge document
   * Permanently removes a document and all its chunks from the knowledge base. Search results will no longer include content from this document.
   * @param id Document ID (required)
   * @throws ApiException if fails to make API call
   */
  public void publicDeleteDocument(@jakarta.annotation.Nonnull UUID id) throws ApiException {
    publicDeleteDocument(id, null);
  }

  /**
   * Delete a knowledge document
   * Permanently removes a document and all its chunks from the knowledge base. Search results will no longer include content from this document.
   * @param id Document ID (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void publicDeleteDocument(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    publicDeleteDocumentWithHttpInfo(id, headers);
  }

  /**
   * Delete a knowledge document
   * Permanently removes a document and all its chunks from the knowledge base. Search results will no longer include content from this document.
   * @param id Document ID (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> publicDeleteDocumentWithHttpInfo(@jakarta.annotation.Nonnull UUID id) throws ApiException {
    return publicDeleteDocumentWithHttpInfo(id, null);
  }

  /**
   * Delete a knowledge document
   * Permanently removes a document and all its chunks from the knowledge base. Search results will no longer include content from this document.
   * @param id Document ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> publicDeleteDocumentWithHttpInfo(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = publicDeleteDocumentRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("publicDeleteDocument", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody != null) {
          localVarResponseBody.readAllBytes();
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder publicDeleteDocumentRequestBuilder(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling publicDeleteDocument");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/knowledge-documents/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a knowledge document by ID
   * Retrieves a single document with its processing status, file name, size, and chunk count. Use this to check whether a recently uploaded document has finished indexing.
   * @param id Document ID (required)
   * @return KnowledgeDocumentResponse
   * @throws ApiException if fails to make API call
   */
  public KnowledgeDocumentResponse publicGetDocument(@jakarta.annotation.Nonnull UUID id) throws ApiException {
    return publicGetDocument(id, null);
  }

  /**
   * Get a knowledge document by ID
   * Retrieves a single document with its processing status, file name, size, and chunk count. Use this to check whether a recently uploaded document has finished indexing.
   * @param id Document ID (required)
   * @param headers Optional headers to include in the request
   * @return KnowledgeDocumentResponse
   * @throws ApiException if fails to make API call
   */
  public KnowledgeDocumentResponse publicGetDocument(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    ApiResponse<KnowledgeDocumentResponse> localVarResponse = publicGetDocumentWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a knowledge document by ID
   * Retrieves a single document with its processing status, file name, size, and chunk count. Use this to check whether a recently uploaded document has finished indexing.
   * @param id Document ID (required)
   * @return ApiResponse&lt;KnowledgeDocumentResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<KnowledgeDocumentResponse> publicGetDocumentWithHttpInfo(@jakarta.annotation.Nonnull UUID id) throws ApiException {
    return publicGetDocumentWithHttpInfo(id, null);
  }

  /**
   * Get a knowledge document by ID
   * Retrieves a single document with its processing status, file name, size, and chunk count. Use this to check whether a recently uploaded document has finished indexing.
   * @param id Document ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;KnowledgeDocumentResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<KnowledgeDocumentResponse> publicGetDocumentWithHttpInfo(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = publicGetDocumentRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("publicGetDocument", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<KnowledgeDocumentResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        KnowledgeDocumentResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<KnowledgeDocumentResponse>() {});
        

        return new ApiResponse<KnowledgeDocumentResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder publicGetDocumentRequestBuilder(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling publicGetDocument");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/knowledge-documents/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a knowledge base by slug
   * Retrieves a knowledge base with its processing status, document count, chunk count, and a list of all documents. Use this to verify that uploaded documents have finished indexing before relying on them in prompts.
   * @param slug Knowledge base handle (required)
   * @return KnowledgeBaseResponse
   * @throws ApiException if fails to make API call
   */
  public KnowledgeBaseResponse publicGetKnowledgeBase(@jakarta.annotation.Nonnull String slug) throws ApiException {
    return publicGetKnowledgeBase(slug, null);
  }

  /**
   * Get a knowledge base by slug
   * Retrieves a knowledge base with its processing status, document count, chunk count, and a list of all documents. Use this to verify that uploaded documents have finished indexing before relying on them in prompts.
   * @param slug Knowledge base handle (required)
   * @param headers Optional headers to include in the request
   * @return KnowledgeBaseResponse
   * @throws ApiException if fails to make API call
   */
  public KnowledgeBaseResponse publicGetKnowledgeBase(@jakarta.annotation.Nonnull String slug, Map<String, String> headers) throws ApiException {
    ApiResponse<KnowledgeBaseResponse> localVarResponse = publicGetKnowledgeBaseWithHttpInfo(slug, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a knowledge base by slug
   * Retrieves a knowledge base with its processing status, document count, chunk count, and a list of all documents. Use this to verify that uploaded documents have finished indexing before relying on them in prompts.
   * @param slug Knowledge base handle (required)
   * @return ApiResponse&lt;KnowledgeBaseResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<KnowledgeBaseResponse> publicGetKnowledgeBaseWithHttpInfo(@jakarta.annotation.Nonnull String slug) throws ApiException {
    return publicGetKnowledgeBaseWithHttpInfo(slug, null);
  }

  /**
   * Get a knowledge base by slug
   * Retrieves a knowledge base with its processing status, document count, chunk count, and a list of all documents. Use this to verify that uploaded documents have finished indexing before relying on them in prompts.
   * @param slug Knowledge base handle (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;KnowledgeBaseResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<KnowledgeBaseResponse> publicGetKnowledgeBaseWithHttpInfo(@jakarta.annotation.Nonnull String slug, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = publicGetKnowledgeBaseRequestBuilder(slug, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("publicGetKnowledgeBase", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<KnowledgeBaseResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        KnowledgeBaseResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<KnowledgeBaseResponse>() {});
        

        return new ApiResponse<KnowledgeBaseResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder publicGetKnowledgeBaseRequestBuilder(@jakarta.annotation.Nonnull String slug, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'slug' is set
    if (slug == null) {
      throw new ApiException(400, "Missing the required parameter 'slug' when calling publicGetKnowledgeBase");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/knowledge-bases/{slug}"
        .replace("{slug}", ApiClient.urlEncode(slug.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Upload documents to a knowledge base
   * Uploads one or more files to a knowledge base for chunking and embedding. Documents are processed asynchronously. Listen for the knowledgedocument.finished webhook or poll the document endpoint to know when they are searchable.
   * @param slug Knowledge base handle (required)
   * @param files  (optional)
   * @return List&lt;KnowledgeDocumentResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<KnowledgeDocumentResponse> publicUploadDocuments(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nullable List<File> files) throws ApiException {
    return publicUploadDocuments(slug, files, null);
  }

  /**
   * Upload documents to a knowledge base
   * Uploads one or more files to a knowledge base for chunking and embedding. Documents are processed asynchronously. Listen for the knowledgedocument.finished webhook or poll the document endpoint to know when they are searchable.
   * @param slug Knowledge base handle (required)
   * @param files  (optional)
   * @param headers Optional headers to include in the request
   * @return List&lt;KnowledgeDocumentResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public List<KnowledgeDocumentResponse> publicUploadDocuments(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nullable List<File> files, Map<String, String> headers) throws ApiException {
    ApiResponse<List<KnowledgeDocumentResponse>> localVarResponse = publicUploadDocumentsWithHttpInfo(slug, files, headers);
    return localVarResponse.getData();
  }

  /**
   * Upload documents to a knowledge base
   * Uploads one or more files to a knowledge base for chunking and embedding. Documents are processed asynchronously. Listen for the knowledgedocument.finished webhook or poll the document endpoint to know when they are searchable.
   * @param slug Knowledge base handle (required)
   * @param files  (optional)
   * @return ApiResponse&lt;List&lt;KnowledgeDocumentResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<KnowledgeDocumentResponse>> publicUploadDocumentsWithHttpInfo(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nullable List<File> files) throws ApiException {
    return publicUploadDocumentsWithHttpInfo(slug, files, null);
  }

  /**
   * Upload documents to a knowledge base
   * Uploads one or more files to a knowledge base for chunking and embedding. Documents are processed asynchronously. Listen for the knowledgedocument.finished webhook or poll the document endpoint to know when they are searchable.
   * @param slug Knowledge base handle (required)
   * @param files  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;List&lt;KnowledgeDocumentResponse&gt;&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<List<KnowledgeDocumentResponse>> publicUploadDocumentsWithHttpInfo(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nullable List<File> files, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = publicUploadDocumentsRequestBuilder(slug, files, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("publicUploadDocuments", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<List<KnowledgeDocumentResponse>>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        List<KnowledgeDocumentResponse> responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<List<KnowledgeDocumentResponse>>() {});
        

        return new ApiResponse<List<KnowledgeDocumentResponse>>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder publicUploadDocumentsRequestBuilder(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nullable List<File> files, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'slug' is set
    if (slug == null) {
      throw new ApiException(400, "Missing the required parameter 'slug' when calling publicUploadDocuments");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/knowledge-bases/{slug}/documents"
        .replace("{slug}", ApiClient.urlEncode(slug.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    MultipartEntityBuilder multiPartBuilder = MultipartEntityBuilder.create();
    boolean hasFiles = false;
    for (int i=0; i < files.size(); i++) {
        multiPartBuilder.addBinaryBody("files", files.get(i));
        hasFiles = true;
    }
    HttpEntity entity = multiPartBuilder.build();
    HttpRequest.BodyPublisher formDataPublisher;
    if (hasFiles) {
        Pipe pipe;
        try {
            pipe = Pipe.open();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        new Thread(() -> {
            try (OutputStream outputStream = Channels.newOutputStream(pipe.sink())) {
                entity.writeTo(outputStream);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }).start();
        formDataPublisher = HttpRequest.BodyPublishers.ofInputStream(() -> Channels.newInputStream(pipe.source()));
    } else {
        ByteArrayOutputStream formOutputStream = new ByteArrayOutputStream();
        try {
            entity.writeTo(formOutputStream);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        byte[] formBytes = formOutputStream.toByteArray();
        formDataPublisher = HttpRequest.BodyPublishers
            .ofInputStream(() -> new ByteArrayInputStream(formBytes));
    }
    localVarRequestBuilder
        .header("Content-Type", entity.getContentType().getValue())
        .method("POST", formDataPublisher);
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
