/*
 * PromptJuggler
 * PromptJuggler API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.promptjuggler.client.api;

import com.promptjuggler.client.ApiClient;
import com.promptjuggler.client.ApiException;
import com.promptjuggler.client.ApiResponse;
import com.promptjuggler.client.Configuration;
import com.promptjuggler.client.Pair;

import com.promptjuggler.client.model.CreateWorkflowRun;
import com.promptjuggler.client.model.CreateWorkflowRunResponse;
import com.promptjuggler.client.model.ErrorResponse;
import java.util.UUID;
import com.promptjuggler.client.model.WorkflowRun;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.23.0")
public class WorkflowRunsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public WorkflowRunsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public WorkflowRunsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create and trigger a workflow run
   * Triggers an asynchronous workflow run with the given inputs and returns a run ID and thread ID. Reference the workflow by version number, tag, or &#x60;__latest__&#x60;. Pass a thread ID to continue an existing conversation across runs.
   * @param slug Workflow Handle (required)
   * @param version Specific version or tag or id (required)
   * @param createWorkflowRun  (required)
   * @return CreateWorkflowRunResponse
   * @throws ApiException if fails to make API call
   */
  public CreateWorkflowRunResponse createWorkflowRun(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nonnull String version, @jakarta.annotation.Nonnull CreateWorkflowRun createWorkflowRun) throws ApiException {
    return createWorkflowRun(slug, version, createWorkflowRun, null);
  }

  /**
   * Create and trigger a workflow run
   * Triggers an asynchronous workflow run with the given inputs and returns a run ID and thread ID. Reference the workflow by version number, tag, or &#x60;__latest__&#x60;. Pass a thread ID to continue an existing conversation across runs.
   * @param slug Workflow Handle (required)
   * @param version Specific version or tag or id (required)
   * @param createWorkflowRun  (required)
   * @param headers Optional headers to include in the request
   * @return CreateWorkflowRunResponse
   * @throws ApiException if fails to make API call
   */
  public CreateWorkflowRunResponse createWorkflowRun(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nonnull String version, @jakarta.annotation.Nonnull CreateWorkflowRun createWorkflowRun, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateWorkflowRunResponse> localVarResponse = createWorkflowRunWithHttpInfo(slug, version, createWorkflowRun, headers);
    return localVarResponse.getData();
  }

  /**
   * Create and trigger a workflow run
   * Triggers an asynchronous workflow run with the given inputs and returns a run ID and thread ID. Reference the workflow by version number, tag, or &#x60;__latest__&#x60;. Pass a thread ID to continue an existing conversation across runs.
   * @param slug Workflow Handle (required)
   * @param version Specific version or tag or id (required)
   * @param createWorkflowRun  (required)
   * @return ApiResponse&lt;CreateWorkflowRunResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateWorkflowRunResponse> createWorkflowRunWithHttpInfo(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nonnull String version, @jakarta.annotation.Nonnull CreateWorkflowRun createWorkflowRun) throws ApiException {
    return createWorkflowRunWithHttpInfo(slug, version, createWorkflowRun, null);
  }

  /**
   * Create and trigger a workflow run
   * Triggers an asynchronous workflow run with the given inputs and returns a run ID and thread ID. Reference the workflow by version number, tag, or &#x60;__latest__&#x60;. Pass a thread ID to continue an existing conversation across runs.
   * @param slug Workflow Handle (required)
   * @param version Specific version or tag or id (required)
   * @param createWorkflowRun  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateWorkflowRunResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateWorkflowRunResponse> createWorkflowRunWithHttpInfo(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nonnull String version, @jakarta.annotation.Nonnull CreateWorkflowRun createWorkflowRun, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createWorkflowRunRequestBuilder(slug, version, createWorkflowRun, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createWorkflowRun", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateWorkflowRunResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateWorkflowRunResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateWorkflowRunResponse>() {});
        

        return new ApiResponse<CreateWorkflowRunResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createWorkflowRunRequestBuilder(@jakarta.annotation.Nonnull String slug, @jakarta.annotation.Nonnull String version, @jakarta.annotation.Nonnull CreateWorkflowRun createWorkflowRun, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'slug' is set
    if (slug == null) {
      throw new ApiException(400, "Missing the required parameter 'slug' when calling createWorkflowRun");
    }
    // verify the required parameter 'version' is set
    if (version == null) {
      throw new ApiException(400, "Missing the required parameter 'version' when calling createWorkflowRun");
    }
    // verify the required parameter 'createWorkflowRun' is set
    if (createWorkflowRun == null) {
      throw new ApiException(400, "Missing the required parameter 'createWorkflowRun' when calling createWorkflowRun");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/workflows/{slug}/{version}/runs"
        .replace("{slug}", ApiClient.urlEncode(slug.toString()))
        .replace("{version}", ApiClient.urlEncode(version.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createWorkflowRun);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a workflow run by ID
   * Retrieves the current state of a workflow run, including status, outputs, aggregated token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
   * @param id Workflow run ID (required)
   * @return WorkflowRun
   * @throws ApiException if fails to make API call
   */
  public WorkflowRun getWorkflowRun(@jakarta.annotation.Nonnull UUID id) throws ApiException {
    return getWorkflowRun(id, null);
  }

  /**
   * Get a workflow run by ID
   * Retrieves the current state of a workflow run, including status, outputs, aggregated token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
   * @param id Workflow run ID (required)
   * @param headers Optional headers to include in the request
   * @return WorkflowRun
   * @throws ApiException if fails to make API call
   */
  public WorkflowRun getWorkflowRun(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    ApiResponse<WorkflowRun> localVarResponse = getWorkflowRunWithHttpInfo(id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a workflow run by ID
   * Retrieves the current state of a workflow run, including status, outputs, aggregated token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
   * @param id Workflow run ID (required)
   * @return ApiResponse&lt;WorkflowRun&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WorkflowRun> getWorkflowRunWithHttpInfo(@jakarta.annotation.Nonnull UUID id) throws ApiException {
    return getWorkflowRunWithHttpInfo(id, null);
  }

  /**
   * Get a workflow run by ID
   * Retrieves the current state of a workflow run, including status, outputs, aggregated token usage, cost, and errors. Poll this endpoint after receiving a webhook notification, or use it to check the status of a run in progress.
   * @param id Workflow run ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;WorkflowRun&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<WorkflowRun> getWorkflowRunWithHttpInfo(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getWorkflowRunRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getWorkflowRun", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<WorkflowRun>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        WorkflowRun responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<WorkflowRun>() {});
        

        return new ApiResponse<WorkflowRun>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getWorkflowRunRequestBuilder(@jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getWorkflowRun");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/api/v1/workflowruns/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
